[package]
name = "yss-database-runtime"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[features]
test-support = []

[dependencies]
arrow.workspace = true
serde_json.workspace = true
thiserror.workspace = true
yss-data-contract = { path = "../yss-data-contract" }
yss-database-contract = { path = "../yss-database-contract" }
yss-database-schema = { path = "../yss-database-schema" }
yss-dataset-profile = { path = "../yss-dataset-profile" }
yss-database-engine = { path = "../yss-database-engine" }
yss-database-store = { path = "../yss-database-store" }
yss-relational-contract = { path = "../yss-relational-contract" }
yss-tabular-contract = { path = "../yss-tabular-contract" }
yss-database-arrow = { path = "../yss-database-arrow" }
yss-database-io = { path = "../yss-database-io" }
uuid.workspace = true
