[package]
name = "yss-database-schema"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
thiserror.workspace = true
yss-data-contract = { path = "../yss-data-contract" }
yss-database-contract = { path = "../yss-database-contract" }
yss-tabular-contract = { path = "../yss-tabular-contract" }
