[package]
name = "yssbi"
version = "0.2.7"
description = "A Tauri App"
authors = ["you"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "3"
members = [".", "sci"]

[workspace.dependencies]
chrono = "0.4.41"
faer = "0.24.0"
ndarray = { version = "0.17.2", features = ["serde"] }
num-traits = "0.2.19"
polars = { version = "0.53.0", default-features = false, features = ["lazy", "csv", "ipc", "parquet", "strings", "dtype-categorical", "dtype-date", "dtype-datetime", "dtype-duration", "dtype-time", "dtype-decimal", "dtype-i8", "dtype-i16", "dtype-u8", "dtype-u16"] }
polars-arrow = { version = "0.53.0", default-features = false }
polars-dtype = { version = "0.53.0", features = ["dtype-categorical"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
statrs = "0.17"


[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "yssbi_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
yss-sci = { path = "./sci" }
tauri = { version = "2.11", features = [] }
tauri-plugin-opener = "2.5.4"
tauri-plugin-dialog = "2.7"
tauri-plugin-fs = "2.5"
tauri-plugin-log = "2"


serde.workspace = true
serde_json.workspace = true
ndarray.workspace = true
polars.workspace = true
polars-arrow.workspace = true
polars-dtype.workspace = true
statrs.workspace = true
chrono.workspace = true
num-traits.workspace = true
faer.workspace = true


uuid = { version = "1.20.0", features = ["v4", "serde"] }
thiserror = "2.0.18"
regex = "1"
mathlex = "=0.4.2"
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "macros", "sqlite", "postgres", "mysql"] }
calamine = "0.26"
rand = "0.8"
duckdb = { version = "1.10504.0", default-features = false, features = ["bundled", "appender-arrow"] }
trash = "5.2"
notify = "8.2.0"
