//! Tauri transport boundary and the canonical YssBI command registry.

mod activity_panel_sync;
mod channel;
mod commands;
mod error;
mod graph_editor_sync;
mod runtime;
mod schema;

pub(crate) use runtime::CommandRuntime;

/// Builds the single invoke handler consumed by the root composition crate.
pub fn invoke_handler() -> impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static {
    use commands::*;

    tauri::generate_handler![
        get_activity_panel_document,
        inspect_ui,
        update_ui,
        request_ui_intent,
        activate_ui_element,
        subscribe_ui,
        unsubscribe_ui,
        pending_ui_intents,
        settle_ui_intent,
        get_localized_node_catalog,
        get_compatible_node_catalog,
        create_event,
        create_function,
        remove_graph,
        unload_project_graph,
        save_project_graph,
        duplicate_graph,
        rename_graph_resource,
        update_function_signature,
        hydrate_editor_graph,
        resolve_editor_graph,
        export_graph_subgraph,
        edit_graph,
        change_graph_history,
        get_graph_edit_receipt,
        subscribe_graph_activity,
        unsubscribe_graph_activity,
        get_execution_run_state,
        get_execution_snapshot,
        allocate_pin_preview_generation,
        execute_graph,
        cancel_graph_run,
        get_result_descriptor,
        retain_result,
        claim_result_lease,
        release_result_lease,
        reconcile_result_leases,
        get_result_value,
        get_result_page,
        get_result_table_page,
        analyze_result,
        get_pin_result,
        get_graph_result_state,
        get_project_databases,
        get_current_project_activation,
        get_project_path,
        get_project_resource_path,
        get_project_index,
        load_project_graph,
        default_project_parent_directory,
        validate_new_project_path,
        list_registered_projects,
        scan_projects_in_directory,
        cancel_project_picker_task,
        cleanup_invalid_registered_projects,
        register_project,
        remove_registered_project,
        delete_registered_project_files,
        toggle_registered_project_favorite,
        get_project_registry_path,
        create_project,
        close_project,
        load_project,
        flush_project,
        save_project_as,
        load_database,
        list_sample_datasets,
        import_sample_dataset,
        list_sqlite_tables,
        list_sql_tables,
        list_excel_sheets,
        delete_database,
        rename_database,
        get_database_meta,
        get_database_rows,
        get_column_stats,
        get_column_distribution,
        get_dataset_overview,
        edit_cell,
        add_row,
        delete_rows,
        add_column,
        delete_column,
        cast_column,
        set_column_semantic,
        rename_column,
        undo_edit,
        redo_edit,
        save_database_changes,
        export_database,
        get_edit_state,
        create_chart,
        duplicate_chart,
        load_chart,
        save_chart,
        rename_chart_resource,
        remove_chart,
        get_plot_column_pair,
        hypothesis_test,
        parse_at_values,
        compute_acf_pacf,
        compute_serial_tests,
        compute_panel_did_fake_group_ri,
        get_harness_runtime_status,
        configure_harness_provider,
        create_harness_session,
        list_harness_sessions,
        open_harness_session,
        subscribe_harness_events,
        unsubscribe_harness_events,
        submit_harness_turn,
        cancel_harness_turn,
        close_harness_session,
        list_harness_memory,
        delete_harness_memory,
        plan_dataset_quality_review,
        advance_harness_workflow,
        pause_harness_workflow,
        resume_harness_workflow,
        cancel_harness_workflow,
        list_plugins,
        inspect_plugin_package,
        install_plugin_package,
        set_plugin_enabled,
        uninstall_plugin,
        attach_plugin_view,
        detach_plugin_view,
        call_plugin_view,
        list_plugin_tasks,
        get_plugin_task_history,
        clear_plugin_task_history,
        get_plugin_storage_usage,
        clear_plugin_cache,
        collect_plugin_garbage,
        get_plugin_diagnostics,
        grant_plugin_export,
    ]
}
