//! Visualization entries awaiting interface and kernel implementation.

use super::*;
use crate::catalog_entry::{self, Entry};

const ENTRIES: &[Entry] = &[
    Entry {
        id: "yssbi.plot.boxplot.view",
        method: "plot.boxplot",
        source_ids: &[226],
        category: CATEGORY,
        en: "Box Plot",
        zh: "箱线图",
        aliases: &["箱线图", "boxplot", "box-and-whisker plot"],
        product_form: "绘图节点",
        scope_note: "",
    },
    Entry {
        id: "yssbi.plot.wordcloud.view",
        method: "plot.wordcloud",
        source_ids: &[227],
        category: CATEGORY,
        en: "Word Cloud",
        zh: "词云",
        aliases: &["词云", "word cloud", "tag cloud"],
        product_form: "绘图节点",
        scope_note: "",
    },
    Entry {
        id: "yssbi.plot.errorbar.view",
        method: "plot.errorbar",
        source_ids: &[228],
        category: CATEGORY,
        en: "Error Bar Plot",
        zh: "误差线图",
        aliases: &["误差线图", "error bars", "uncertainty"],
        product_form: "绘图节点",
        scope_note: "",
    },
    Entry {
        id: "yssbi.plot.pp_qq.view",
        method: "plot.pp_qq",
        source_ids: &[229],
        category: CATEGORY,
        en: "P-P / Q-Q Plot",
        zh: "P-P/Q-Q图",
        aliases: &[
            "P-P/Q-Q图",
            "P-P",
            "Q-Q",
            "probability plot",
            "quantile plot",
        ],
        product_form: "绘图节点",
        scope_note: "P-P 和 Q-Q 是不同图形，需明确参考分布和参数估计规则。",
    },
    Entry {
        id: "yssbi.plot.roc.view",
        method: "plot.roc",
        source_ids: &[230],
        category: CATEGORY,
        en: "ROC Curve",
        zh: "ROC曲线",
        aliases: &["ROC曲线", "ROC", "receiver operating characteristic"],
        product_form: "绘图节点",
        scope_note: "",
    },
    Entry {
        id: "yssbi.plot.quadrant.view",
        method: "plot.quadrant",
        source_ids: &[231],
        category: CATEGORY,
        en: "Quadrant Plot",
        zh: "象限图",
        aliases: &["象限图", "quadrant chart"],
        product_form: "绘图节点",
        scope_note: "",
    },
    Entry {
        id: "yssbi.plot.pareto.view",
        method: "plot.pareto",
        source_ids: &[232],
        category: CATEGORY,
        en: "Pareto Chart",
        zh: "帕累托图",
        aliases: &["帕累托图", "Pareto", "80/20"],
        product_form: "绘图节点",
        scope_note: "",
    },
    Entry {
        id: "yssbi.plot.combination.view",
        method: "plot.combination",
        source_ids: &[234],
        category: CATEGORY,
        en: "Combination Chart",
        zh: "组合图",
        aliases: &["组合图", "combo chart", "mixed chart"],
        product_form: "绘图节点",
        scope_note: "组合图需明确可组合图种、轴与图例规则。",
    },
    Entry {
        id: "yssbi.plot.bubble.view",
        method: "plot.bubble",
        source_ids: &[235],
        category: CATEGORY,
        en: "Bubble Chart",
        zh: "气泡图",
        aliases: &["气泡图", "bubble plot"],
        product_form: "绘图节点",
        scope_note: "",
    },
    Entry {
        id: "yssbi.plot.violin.view",
        method: "plot.violin",
        source_ids: &[237],
        category: CATEGORY,
        en: "Violin Plot",
        zh: "小提琴图",
        aliases: &["小提琴图", "violin plot", "distribution"],
        product_form: "绘图节点",
        scope_note: "",
    },
    Entry {
        id: "yssbi.plot.heatmap.view",
        method: "plot.heatmap",
        source_ids: &[238],
        category: CATEGORY,
        en: "Heatmap",
        zh: "热力图",
        aliases: &["热力图", "heat map", "matrix plot"],
        product_form: "绘图节点",
        scope_note: "",
    },
    Entry {
        id: "yssbi.plot.coefficient.view",
        method: "plot.coefficient",
        source_ids: &[239],
        category: CATEGORY,
        en: "Coefficient Plot",
        zh: "Coef图",
        aliases: &["Coef图", "coefficient plot", "Coef", "coefplot"],
        product_form: "绘图节点",
        scope_note: "",
    },
];

pub(super) fn append(fragment: &mut ProviderFragment) -> Result<(), BuiltinAssemblyError> {
    catalog_entry::append(ENTRIES, fragment, "builtin.plot", "builtin.plot")
}

pub(crate) fn documentation(id: &str, locale: &str) -> Option<Box<str>> {
    catalog_entry::documentation(ENTRIES, id, locale)
}
