[package]
name = "yss-database-io"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
calamine = "0.36"
chrono.workspace = true
arrow.workspace = true
parquet.workspace = true
thiserror.workspace = true
yss-database-arrow = { path = "../yss-database-arrow" }

[dev-dependencies]
serde_json.workspace = true
