[package]
name = "yss-tabular-io"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
calamine = "0.36"
arrow.workspace = true
parquet.workspace = true
thiserror.workspace = true
yss-tabular-contract = { path = "../yss-tabular-contract" }
yss-tabular-arrow = { path = "../yss-tabular-arrow" }

[dev-dependencies]
serde_json.workspace = true
