[package]
name = "yss-sci"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray.workspace = true
ndarray-stats.workspace = true
polars.workspace = true
faer = "0.24.0"
statrs = "0.17"
num-traits = "0.2.19"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
csv = "1.3"
