[package]
name = "yss-sci"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
faer.workspace = true
ndarray.workspace = true
num-traits.workspace = true
polars.workspace = true
serde.workspace = true
serde_json.workspace = true
statrs.workspace = true

[dev-dependencies]
csv = "1.3"