[package]
name = "yss-project-model"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
serde.workspace = true
yss-database-contract = { path = "../yss-database-contract" }
yss-graph-document = { path = "../yss-graph-document" }
yss-project-history = { path = "../yss-project-history" }
yss-project-identity = { path = "../yss-project-identity" }
yss-variable-contract = { path = "../yss-variable-contract" }
yss-chart-document = { path = "../yss-chart-document" }

[dev-dependencies]
serde_json.workspace = true
