[package]
name = "yss-ipc-channel"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
tauri.workspace = true
thiserror.workspace = true
uuid.workspace = true
yss-ipc-contract = { path = "../yss-ipc-contract" }
yss-automation-contract = { path = "../yss-automation-contract" }
yss-project-progress = { path = "../yss-project-progress" }

[dev-dependencies]
serde_json.workspace = true
