[package]
name = "yss-duckdb"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
duckdb.workspace = true
polars.workspace = true
polars-arrow.workspace = true
polars-dtype.workspace = true
thiserror.workspace = true
yss-database-contract = { path = "../yss-database-contract" }
yss-dataset-profile = { path = "../yss-dataset-profile" }
yss-tabular-io = { path = "../yss-tabular-io" }
