[package]
name = "yss-julia-worker"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
yss-file-replace = { path = "../yss-file-replace" }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
uuid.workspace = true
yss-julia-runtime = { path = "../yss-julia-runtime" }
