[package]
name = "yss-variable-contract"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
yss-data-contract = { path = "../yss-data-contract" }
yss-tabular-contract = { path = "../yss-tabular-contract" }
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true
