/**
 * Application-owned view capability surface.
 *
 * Views consume this module instead of reaching into Core stores, Domain
 * helpers, or IPC services directly. The lower-level implementations remain
 * behind this composition boundary until their individual owners are moved.
 */
import * as coreCanvasConnection from '@/features/core/canvas/connectionInteraction';
import * as coreCanvas from '@/features/core/canvas';
import * as coreDataStore from '@/features/core/dataStore';
import * as coreDnd from '@/features/core/dnd';
import * as coreDockview from '@/features/core/dockview';
import * as coreEditor from '@/features/core/editor';
import * as coreExecution from '@/features/core/execution';
import * as coreGraphInteraction from '@/features/core/graphInteraction/graphInteractionStore';
import * as coreGraphSession from '@/features/core/graphSession/graphSessionStore';
import * as coreKeyboard from '@/features/core/keyboard';
import * as coreLayout from '@/features/core/layout';
import * as coreLogDomains from '@/features/core/log/logDomains';
import * as coreLogBuffer from '@/features/core/log/logBuffer';
import * as coreLogStore from '@/features/core/log/logStore';
import * as coreLiveLogs from '@/features/core/log/useLiveLogs';
import * as coreNode from '@/features/core/node';
import * as corePin from '@/features/core/pin';
import * as corePlugin from '@/features/core/plugins/pluginStore';
import * as coreProjectLifecycle from '@/features/core/projectLifecycle/projectLifecycleAuthority';
import * as coreResource from '@/features/core/resource';
import * as coreResultSource from '@/features/core/resultSource';
import * as coreSidebar from '@/features/core/sidebar';
import * as coreSidebarDrag from '@/features/core/sidebarDrag';
import * as coreStatusBar from '@/features/core/statusBar';
import * as coreUi from '@/features/core/ui/UIStore';
import * as coreViewport from '@/features/core/viewport';
import * as coreWorkbench from '@/features/core/workbench';
import * as coreDataDatabase from '@/features/core/dataStore/databaseStore';
import * as coreDataGraph from '@/features/core/dataStore/graphDataStore';
import * as coreDataDocument from '@/features/core/resource/documentStateStore';
import * as applicationProjectStore from '@/features/application/project/projectIOStore';
import * as applicationProjectSession from '@/features/application/project/projectSession';
import * as coreDataVariable from '@/features/core/dataStore/variableStore';
import * as coreSettingsStore from '@/features/core/settings/settingsStore';
import * as coreWorksheetStore from '@/features/core/worksheet/worksheetStore';
import * as coreDockviewLogs from '@/features/core/dockview/logsDockviewLayout';
import * as coreDockviewLogsController from '@/features/core/dockview/logsDockviewLayoutController';
import * as coreDockviewDefaults from '@/features/core/dockview/workbenchDockviewDefaults';
import * as coreDockviewRead from '@/features/core/dockview/workbenchRead';
import * as coreDockviewControl from '@/features/core/dockview/workbenchControl';
import * as coreDockviewRootBinding from '@/features/core/dockview/workbenchRootBinding';
import * as coreLogsRead from '@/features/core/dockview/logsRead';
import * as coreLogsControl from '@/features/core/dockview/logsControl';
import * as coreLogsRootBinding from '@/features/core/dockview/logsRootBinding';
import * as coreGraphNodeAccess from '@/features/core/dataStore/graphEntityAccess';
import * as corePinLinks from '@/features/core/dataStore/pinLinks';
import * as coreSidebarTree from '@/features/core/sidebar/projectTreeState';
import * as coreThemePin from '@/features/core/theme/pinTypeTheme';
import * as coreViewportSession from '@/features/core/viewport/viewportSession';
import * as coreViewportScope from '@/features/core/viewport/viewportScope';
import * as coreCanvasPreview from '@/features/core/canvas/connectPreview';
import * as coreApplicationNodeView from '@/features/core/dataStore/nodeView';
import * as coreApplicationUseNodeView from '@/features/core/dataStore/useNodeView';

import * as domainBayes from '@/features/domain/bayes';
import * as domainNode from '@/features/domain/node/utils';
import * as domainNodeCatalog from '@/features/domain/nodeCatalog/creationDescriptor';
import * as domainCatalogItem from '@/features/domain/nodeCatalog/catalogItem';
import * as domainCatalogTree from '@/features/domain/nodeCatalog/localizedCatalogTree';
import * as domainSidebar from '@/features/domain/sidebar';
import * as domainCanvas from '@/features/domain/canvas/edgeData';

import * as projectService from '@/services/project/projectService';
import * as databaseService from '@/services/database/databaseService';
import * as worksheetService from '@/services/worksheet/worksheetService';
import * as worksheetDataService from '@/services/worksheet/worksheetDataService';
import * as worksheetPreviewCache from '@/services/worksheet/worksheetPreviewCache';
import * as ipcService from '@/services/ipc';
import * as pathDialog from '@/services/platform/pathDialog';
import * as coreGraphRead from '@/features/core/graph/read';
import * as coreResultValuePayload from '@/features/core/resultSource/resultValuePayload';
import * as coreResultReadError from '@/features/core/resultSource/components/ResultReadError';
import * as coreResultPresentation from '@/features/core/resultSource/resultViewPresentation';
import * as coreResultTypes from '@/features/core/resultSource/types';
import * as coreHistoryTypes from '@/features/core/history/types';
import { addGlobalEventListener as addGlobalEventListenerImpl } from '@/shared/utils/globalEvent';
import { useTheme as useThemeImpl } from '@/features/core/theme/useTheme';
import { initializeProjectForCurrentWindow } from '@/features/application/project';
import { getGraphByPath as getGraphByPathImpl } from '@/features/application/project/projectHelpers';
import * as coreViewportTransform from '@/features/core/viewport/viewportTransform';
import * as coreExecutionPlayback from '@/features/core/execution/useExecutionPlayback';
import * as coreExecutionArtifacts from '@/features/core/execution/graphRunArtifacts';
import * as coreExecutionPinIndex from '@/features/core/execution/pinResultIndex';
import * as coreExecutionPinTarget from '@/features/core/execution/pinViewTarget';
import * as coreDndModifier from '@/features/core/dnd/snapTopLeftToCursorModifier';
import * as coreSidebarFlatRows from '@/features/core/sidebar/flatRows';
import * as coreEditorDetailTypes from '@/features/core/editor/detail/types';
import * as coreResourceFunctionView from '@/features/core/resource/functionResourceView';
import * as coreResourceSelectors from '@/features/core/resource/resourceSelectors';
import * as coreDomainBayesDiagnostics from '@/features/domain/bayes/diagnostics';
import * as coreDomainCatalogItem from '@/features/domain/nodeCatalog/catalogItem';
import * as coreDomainNodeNames from '@/features/domain/node/utils/nodeClassNames';
import * as coreDomainDiagnostics from '@/features/domain/graphDiagnostics/nodeDiagnostics';

export const useGraphDataStore = coreDataGraph.useGraphDataStore;
export const useGraphMetaStore = coreDataStore.useGraphMetaStore;
export const useProjectIOStore = applicationProjectStore.useProjectIOStore;
export const useDatabaseStore = coreDataDatabase.useDatabaseStore;
export const useVariableStore = coreDataVariable.useVariableStore;
export const useDocumentStateStore = coreDataDocument.useDocumentStateStore;
export const useResourceStore = coreResource.useResourceStore;
export const useWorksheetStore = coreWorksheetStore.useWorksheetStore;
export const useSettingsStore = coreSettingsStore.useSettingsStore;
export const useExecutionStore = coreExecution.useExecutionStore;
export const useGraphSessionStore = coreGraphSession.useGraphSessionStore;
export const useGraphInteractionStore = coreGraphInteraction.useGraphInteractionStore;
export const useEditorStore = coreEditor.useEditorStore;
export const useWorkbenchStore = coreWorkbench.useWorkbenchStore;
export const useSidebarDragStore = coreSidebarDrag.useSidebarDragStore;
export const usePluginStore = corePlugin.usePluginStore;
export const useLogStore = coreLogStore.useLogStore;
export const uiStore = coreUi.uiStore;

export const GroupContext = coreEditor.GroupContext;
export const useEditorGroupWorkspace = coreEditor.useEditorGroupWorkspace;
export const useActiveEditorGroup = coreEditor.useActiveEditorGroup;
export const useActiveProjectPath = applicationProjectSession.useActiveProjectPath;
export const useDetailTarget = coreEditor.useDetailTarget;
export const useFunctionCatalog = coreEditor.useFunctionCatalog;
export const useNodeView = coreApplicationUseNodeView.useNodeView;
export const useNodeStyle = coreNode.useNodeStyle;
export const useNodeExecution = coreNode.useNodeExecution;
export const usePinInput = corePin.usePinInput;
export const useRepeatablePinRemovable = corePin.useRepeatablePinRemovable;
export const useTheme = useThemeImpl;
export const getPinTypeColor = coreThemePin.getPinTypeColor;
export const getCanvasInteraction = coreGraphInteraction.getCanvasInteraction;
export const getPositionOverride = coreGraphInteraction.getPositionOverride;
export const getExecutionVisual = coreExecution.getExecutionVisual;
export const subscribeExecutionVisual = coreExecution.subscribeExecutionVisual;
export const connectionKey = coreExecution.connectionKey;
export const useExecutionVisualBinder = coreExecution.useExecutionVisualBinder;
export const recordingHadError = coreExecution.recordingHadError;
export const useExecutionPlayback = coreExecutionPlayback.useExecutionPlayback;
export const graphHasClearableArtifacts = coreExecutionArtifacts.graphHasClearableArtifacts;
export const buildPinViewParams = coreExecutionPinTarget.buildPinViewParams;
export const evaluatePinViewState = coreExecutionPinTarget.evaluatePinViewState;
export const pinViewDisabledTitle = coreExecutionPinTarget.pinViewDisabledTitle;
export const pinHistoryCacheKey = coreExecutionPinIndex.pinHistoryCacheKey;
export const getGraphByPath = getGraphByPathImpl;
export const initProjectSync = initializeProjectForCurrentWindow;
export const resourceKey = coreResource.resourceKey;
export const getActiveLayoutTab = coreLayout.getActiveLayoutTab;
export const updateEditorGroupSelectedNodeIds = coreLayout.updateEditorGroupSelectedNodeIds;
export const getGraphSnapshot = coreGraphRead.getGraphSnapshot;
export const useGraphRead = coreGraphRead.useGraphRead;
export const useGraphResourcesByKind = coreResource.useGraphResourcesByKind;
export const useSidebarSectionExpandSnapshot = coreSidebar.useSidebarSectionExpandSnapshot;
export const useLiveLogs = coreLiveLogs.useLiveLogs;
export const useDetailTargetRead = coreEditor.useDetailTarget;
export const useViewportStore = coreViewport.useViewportStore;
export const getViewport = coreViewportSession.getViewport;
export const subscribeToViewport = coreViewportSession.subscribeToViewport;
export const editorViewportScope = coreViewportScope.editorViewportScope;
export const applyViewportTransform = coreViewportTransform.applyViewportTransform;
export const viewportTransformStyle = coreViewportTransform.viewportTransformStyle;
export const applyViewportGrid = coreViewportTransform.applyViewportGrid;
export const viewportGridStyle = coreViewportTransform.viewportGridStyle;
export const useModifierKeyStore = coreKeyboard.useModifierKeyStore;
export const useResultValue = coreResultSource.useResultValue;
export const reportResultValuePayload = coreResultValuePayload.reportResultValuePayload;
export const ResultReadError = coreResultReadError.ResultReadError;
export const UnifiedResultView = coreResultSource.UnifiedResultView;
export const ResultViewPresentationProvider = coreResultPresentation.ResultViewPresentationProvider;
export const useResultViewPresentation = coreResultPresentation.useResultViewPresentation;
export const useStatusBarSnapshot = coreStatusBar.useStatusBarSnapshot;
export const useSidebarStore = coreSidebar.useSidebarStore;
export const applyLogFilter = coreLogStore.applyLogFilter;
export const logBuffer = coreLogBuffer.logBuffer;
export const isLogDomainId = coreLogDomains.isLogDomainId;
export const logsDockviewLayoutController = coreDockviewLogsController.logsDockviewLayoutController;
export const workbenchDockviewPort = coreDockview.workbenchDockviewPort;
export const workbenchDockviewRead = coreDockviewRead.workbenchDockviewRead;
export const workbenchDockviewControl = coreDockviewControl.workbenchDockviewControl;
export const workbenchDockviewRootBinding = coreDockviewRootBinding.workbenchDockviewRootBinding;
export const logsDockviewRead = coreLogsRead.logsDockviewRead;
export const logsDockviewControl = coreLogsControl.logsDockviewControl;
export const logsDockviewRootBinding = coreLogsRootBinding.logsDockviewRootBinding;
export const workbenchLayoutController = coreDockview.workbenchDockviewPort;
export const WORKBENCH_ACTIVITY_GROUP_ID = coreDockviewDefaults.WORKBENCH_ACTIVITY_GROUP_ID;
export const getSidebarDragOverlayLabel = coreDnd.getSidebarDragOverlayLabel;
export const DRAG_TYPES = coreDnd.DRAG_TYPES;
export const DROP_TYPES = coreDnd.DROP_TYPES;
export const getCanvasDropZoneId = coreDnd.getCanvasDropZoneId;
export const getConnectPreview = coreCanvasPreview.getConnectPreview;
export const subscribeConnectPreview = coreCanvasPreview.subscribeConnectPreview;
export const useNodeDragPreview = coreCanvas.useNodeDragPreview;
export const useEdgeDragPreview = coreCanvas.useEdgeDragPreview;
export const useSelectionBoxPreview = coreCanvas.useSelectionBoxPreview;
export const computeEdgePath = coreCanvas.computeEdgePath;
export const findInternalNodeInGraph = coreDataStore.findInternalNodeInGraph;
export const derivePinConnectionView = corePinLinks.derivePinConnectionView;
export const toUiNode = coreApplicationNodeView.toUiNode;
export const uiNodeHasNoHeader = coreApplicationNodeView.uiNodeHasNoHeader;
export const uiNodeIsReroute = coreApplicationNodeView.uiNodeIsReroute;
export const getPaneSelection = coreDockview.getPaneSelection;
export const useEditorPaneStateStore = coreDockview.useEditorPaneStateStore;
export const componentForWorkbenchMetadata = coreDockview.componentForWorkbenchMetadata;
export const isWorkbenchPanelMetadata = coreDockview.isWorkbenchPanelMetadata;
export const isWorkbenchActivityMetadata = coreDockview.isWorkbenchActivityMetadata;
export const isWorkbenchActivityViewId = coreDockview.isWorkbenchActivityViewId;
export const isWorkbenchPersistentViewMetadata = coreDockview.isWorkbenchPersistentViewMetadata;
export const layoutTabFromEditorMetadata = coreDockview.layoutTabFromEditorMetadata;
export const resolveActiveProjectPath = applicationProjectSession.resolveActiveProjectPath;
export const captureProjectIdentity = coreProjectLifecycle.captureProjectIdentity;
export const isCurrentProjectIdentity = coreProjectLifecycle.isCurrentProjectIdentity;
export const assertCurrentProjectIdentity = coreProjectLifecycle.assertCurrentProjectIdentity;
export const addGlobalEventListener = addGlobalEventListenerImpl;
export const snapTopLeftToCursor = coreDndModifier.snapTopLeftToCursor;
export const buildSidebarDragState = coreDnd.buildSidebarDragState;
export const isSidebarSpawnDrag = coreDnd.isSidebarSpawnDrag;
export const parseCanvasDragPayload = coreDnd.parseCanvasDragPayload;
export const buildDataSidebarModel = coreSidebarFlatRows.buildDataSidebarModel;
export const SIDEBAR_FLAT_ROW_HEIGHT = coreSidebarFlatRows.SIDEBAR_FLAT_ROW_HEIGHT;
export const PROJECT_TREE_CATEGORY_IDS = coreSidebarTree.PROJECT_TREE_CATEGORY_IDS;
export const DEFAULT_LOGS_DOCKVIEW_LAYOUT = coreDockviewLogs.DEFAULT_LOGS_DOCKVIEW_LAYOUT;
export const LOGS_DOCKVIEW_COMPONENT_ID = coreDockviewLogs.LOGS_DOCKVIEW_COMPONENT_ID;

export const ProjectService = projectService.ProjectService;
export const DatabaseService = databaseService.DatabaseService;
export const WorksheetService = worksheetService.WorksheetService;
export const fetchWorksheetPreview = worksheetDataService.fetchWorksheetPreview;
export const getCachedWorksheetPreview = worksheetPreviewCache.getCachedWorksheetPreview;
export const getWorksheetPreview = worksheetPreviewCache.getWorksheetPreview;
export const toErrorReference = ipcService.toErrorReference;
export const openPathDialog = pathDialog.openPathDialog;

export const defaultPriorForConstraint = domainBayes.defaultPriorForConstraint;
export const formatPrior = domainBayes.formatPrior;
export const issueTargetStep = domainBayes.issueTargetStep;
export const formatExpression = domainBayes.formatExpression;
export const formatRawExpressionLatex = domainBayes.formatRawExpressionLatex;
export const evaluateInferenceDiagnostics = coreDomainBayesDiagnostics.evaluateInferenceDiagnostics;
export const parameterDiagnosticStatus = coreDomainBayesDiagnostics.parameterDiagnosticStatus;
export const diagnosticSeverityClass = coreDomainBayesDiagnostics.diagnosticSeverityClass;
export const getNodeClassName = domainNode.getNodeClassName;
export const getNodeBackgroundStyle = domainNode.getNodeBackgroundStyle;
export const getNodeMinSize = domainNode.getNodeMinSize;
export const PIN_COLORS = domainSidebar.PIN_COLORS;
export const TYPE_ICON_COLORS = domainSidebar.TYPE_ICON_COLORS;
export const catalogItemKey = domainCatalogItem.catalogItemKey;
export const REROUTE_NODE_WIDTH_PX = coreDomainNodeNames.REROUTE_NODE_WIDTH_PX;
export const REROUTE_NODE_HEIGHT_PX = coreDomainNodeNames.REROUTE_NODE_HEIGHT_PX;
export const REROUTE_GRIP_SIZE_PX = coreDomainNodeNames.REROUTE_GRIP_SIZE_PX;
export const collectNodeDiagnostics = coreDomainDiagnostics.collectNodeDiagnostics;

export type ProjectActivationResult = projectService.ProjectActivationResult;
export type RevealProjectResourceRequest = projectService.RevealProjectResourceRequest;
export type LogsDockviewPanelParams = coreDockviewLogs.LogsDockviewPanelParams;
export type LogsDockviewLayoutController = coreDockviewLogsController.LogsDockviewLayoutController;
export type EditorResourceKind = coreDockview.EditorResourceKind;
export type WorkbenchPanelParams = coreDockview.WorkbenchPanelParams;
export type WorkbenchPanelInfo = coreDockview.WorkbenchPanelInfo;
export type WorkbenchComponentId = coreDockview.WorkbenchComponentId;
export type WorkbenchPanelMetadata = coreDockview.WorkbenchPanelMetadata;
export type WorkbenchViewId = coreDockview.WorkbenchViewId;
export type WorkbenchActivityViewId = coreDockview.WorkbenchActivityViewId;
export type FunctionResourceView = coreResourceFunctionView.FunctionResourceView;
export type GraphResourceRecord = coreResourceSelectors.GraphResourceRecord;
export type StatusBarItemViewModel = coreStatusBar.StatusBarItemViewModel;
export type SidebarDragPayload = coreDnd.SidebarDragPayload;
export type NodeTemplateDragData = coreDnd.NodeTemplateDragData;
export type NodeCreationDescriptor = domainNodeCatalog.NodeCreationDescriptor;
export type LocalizedCatalogBrowserRow = domainCatalogTree.LocalizedCatalogBrowserRow;
export type EdgeData = domainCanvas.EdgeData;
export type ConnectionFeedback = coreCanvasConnection.ConnectionFeedback;
export type DetailTarget = coreEditorDetailTypes.DetailTarget;
export type EditorDataframes = coreEditor.EditorDataframes;
export type GraphEntitiesState = coreGraphNodeAccess.GraphEntitiesState;
export type SidebarSectionActionConfig = coreSidebar.SidebarSectionActionConfig;
export type SidebarSectionKey = coreSidebar.SidebarSectionKey;
export type SidebarProjectTreeCategoryId = coreSidebarTree.ProjectTreeCategoryId;
export type ProjectTreeCategoryId = coreSidebarTree.ProjectTreeCategoryId;
export type SidebarPanelModel = coreSidebarFlatRows.SidebarPanelModel;
export type SidebarItemRow = coreSidebarFlatRows.SidebarItemRow;
export type DiagnosticSuggestion = coreDomainBayesDiagnostics.DiagnosticSuggestion;
export type GraphNodeDiagnostic = coreDomainDiagnostics.GraphNodeDiagnostic;
export type LocalizedCatalogItem = coreDomainCatalogItem.LocalizedCatalogItem;
export type ReportKind = coreResultTypes.ReportKind;
export type ResultDescriptor = coreResultTypes.ResultDescriptor;
export type LogDomainId = coreLogDomains.LogDomainId;
export type DiagnosticLogFilter = coreLogStore.DiagnosticLogFilter;
export type GraphMutationCommandResult = coreHistoryTypes.GraphMutationCommandResult;
export type ViewportScope = coreViewport.ViewportScope;
export type PinHistoryProjection = import('@/shared/types/ui/execution').PinHistoryProjection;
