[package]
name = "yss-tracing"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
file-rotate = "0.8.0"
regex.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-log = "0.2.0"
tracing-subscriber.workspace = true
