[package]
name = "yss-database-io"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
calamine = "0.36"
arrow.workspace = true
parquet.workspace = true
thiserror.workspace = true
yss-data-contract = { path = "../yss-data-contract" }
yss-database-arrow = { path = "../yss-database-arrow" }

[dev-dependencies]
serde_json.workspace = true
