use crate::architecture_tests::model::RustDebtEntry;

use super::EXECUTION_RUNTIME_SPEC;

pub(super) fn extend(entries: &mut Vec<RustDebtEntry>) {
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/builtin.rs",
        "yssbi_lib::node_system::runtime::builtin",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::data_series::DataSeriesBuilder"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::data_series::DataSeriesElementType"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::kernel::KernelContext"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::kernel::KernelError"
            ),
            (Use, 1, "yssbi_lib::node_system::runtime::run::ArtifactKind"),
            (Use, 1, "yssbi_lib::node_system::runtime::run::RuntimeValue"),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::data_series::require_data_series"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::project_resource::ProjectResourceLease"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::project_resource::ProjectResourceLease::variable_access"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/data_series.rs",
        "yssbi_lib::node_system::runtime::data_series",
        [
            (Use, 2, "yssbi_lib::node_system::protocol::types::TypeExpr"),
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
            (
                Path,
                1,
                "yssbi_lib::node_system::protocol::data_series::DATA_SERIES_CONSTRUCTOR_ID"
            ),
            (Path, 2, "yssbi_lib::node_system::protocol::types::TypeExpr"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/execution_event.rs",
        "yssbi_lib::node_system::runtime::execution_event",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::document::model::GraphResourcePath"
            ),
            (Use, 1, "yssbi_lib::node_system::identity::ProjectSessionId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::GraphOutputRef"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/function_plan.rs",
        "yssbi_lib::node_system::runtime::function_plan",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceKey"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceVersion"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceVersionSet"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::model::GraphResourcePath"
            ),
            (Use, 1, "yssbi_lib::node_system::identity::ProjectSessionId"),
            (Use, 1, "yssbi_lib::node_system::plan::model::ExecutionPlan"),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::FunctionPlanAbi"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::FunctionPlanHandle"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::validation::PlanSourceFacts"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::registry::fingerprint::RegistryFingerprint"
            ),
            (Path, 1, "yssbi_lib::node_system::plan::model::ValueRef"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/kernel.rs",
        "yssbi_lib::node_system::runtime::kernel",
        [
            (Use, 1, "yssbi_lib::node_system::document::ids::NodeId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::model::GraphResourcePath"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::CompiledParameterHandle"
            ),
            (Use, 1, "yssbi_lib::node_system::plan::model::KernelHandle"),
            (
                Use,
                1,
                "yssbi_lib::project::computation_settings::NumericTolerance"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::computation_settings::ProjectComputationSettings"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::computation_settings::StatisticalMissingValuePolicy"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/kernels/core_nodes/control.rs",
        "yssbi_lib::node_system::runtime::kernels::core_nodes::control",
        [(Use, 1, "yssbi_lib::node_system::protocol::value::Value")],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/kernels/core_nodes/debug.rs",
        "yssbi_lib::node_system::runtime::kernels::core_nodes::debug",
        [(Use, 1, "yssbi_lib::node_system::protocol::value::Value")],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/kernels/core_nodes/math.rs",
        "yssbi_lib::node_system::runtime::kernels::core_nodes::math",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::protocol::value::CanonicalDecimal"
            ),
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/kernels/core_nodes/value.rs",
        "yssbi_lib::node_system::runtime::kernels::core_nodes::value",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::protocol::value::CanonicalDecimal"
            ),
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/kernels/dataframe/mod.rs",
        "yssbi_lib::node_system::runtime::kernels::dataframe",
        [
            (Use, 1, "yssbi_lib::node_system::plan::model::ResourceId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::protocol::value::CanonicalDecimal"
            ),
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/kernels/distribution/mod.rs",
        "yssbi_lib::node_system::runtime::kernels::distribution",
        [(
            Use,
            1,
            "yssbi_lib::node_system::protocol::value::CanonicalDecimal"
        )],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state.rs",
        "yssbi_lib::project::project_state",
        [
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::result::PinResultEntry"
            ),
            (Path, 1, "yssbi_lib::node_system::runtime::result::ResultId"),
            (
                Path,
                2,
                "yssbi_lib::node_system::runtime::result::StoredResult"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/compile_resources.rs",
        "yssbi_lib::project::project_state::compile_resources",
        [
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::kernels::plot::PlotKind"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::kernels::plot::PlotPublishError"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::kernels::plot::PlotSink"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::project_resource::ProjectResourceSnapshot"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/errors.rs",
        "yssbi_lib::project::project_state::errors",
        [
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::execution_event::RunErrorOutcome::DeadlineExceeded"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::execution_event::RunErrorOutcome::Ordinary"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::execution_event::RunErrorOutcome::from"
            ),
            (Path, 4, "yssbi_lib::node_system::runtime::run::RunError"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/execution.rs",
        "yssbi_lib::project::project_state::execution",
        [
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::execution_event::RunEventSink"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::function_plan::FunctionPlanStore"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::kernel::KernelRegistry"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::memoization::SessionMemoization"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::parameters::CompiledParameterStore::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::production_relational::ProductionRelationalBackend::default"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::project_resource::ProjectResourceProvider::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::project_resource::ProjectResourceSnapshot::new"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::runtime::project_run::ProjectRunRegistry"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::relational::RelationalBackendRegistry::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::result_store::ResultStore"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::runtime::run::CancellationToken"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::run::CancellationToken::new"
            ),
            (Path, 2, "yssbi_lib::node_system::runtime::run::RunDeadline"),
            (
                Path,
                3,
                "yssbi_lib::node_system::runtime::run::RunError::from"
            ),
            (Path, 1, "yssbi_lib::node_system::runtime::run::RunId"),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::run::RunPhase::ResultPublication"
            ),
            (Path, 3, "yssbi_lib::node_system::runtime::run::RunResult"),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::scheduler::RunExecutor::new"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/run_parameters.rs",
        "yssbi_lib::project::project_state::run_parameters",
        [
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::function_plan::FunctionPlanGeneration"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::function_plan::FunctionPlanStore"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::kernels::dataframe::DataframeKernelParameters"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::kernels::statistics::StatisticsKernelParameters"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::runtime::parameters::CompiledParameterStore"
            ),
            (
                Path,
                2,
                "yssbi_lib::sci::models::regression::StatisticalSettingSource::Node"
            ),
            (
                Path,
                2,
                "yssbi_lib::sci::models::regression::StatisticalSettingSource::Project"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/variable_effects.rs",
        "yssbi_lib::project::project_state::variable_effects",
        [
            (
                Path,
                2,
                "yssbi_lib::node_system::runtime::project_resource::VariableWriteEffect"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::runtime::run::CancellationToken"
            ),
            (Path, 3, "yssbi_lib::node_system::runtime::run::RunDeadline"),
            (Path, 1, "yssbi_lib::node_system::runtime::run::RunError"),
            (
                Path,
                2,
                "yssbi_lib::node_system::runtime::run::RunError::Cancelled"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::runtime::run::RunError::DeadlineExceeded"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::run::RunError::ResourceSnapshotMismatch"
            ),
            (Path, 1, "yssbi_lib::node_system::runtime::run::RunPhase"),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::run::RunPhase::ResultPublication"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_store.rs",
        "yssbi_lib::project::project_store",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::function_plan::FunctionPlanStore"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::kernel::KernelRegistry"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::memoization::SessionMemoization"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::parameters::CompiledParameterStore"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::project_run::ProjectRunRegistry"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::result_store::ResultStore"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/sci/api/bayes/expression.rs",
        "yssbi_lib::sci::api::bayes::expression",
        [
            (Use, 1, "yssbi_lib::math::ParseOptions"),
            (Use, 1, "yssbi_lib::math::ir::BinaryOp"),
            (Use, 1, "yssbi_lib::math::ir::ComparisonOp"),
            (Use, 1, "yssbi_lib::math::ir::MathExpr"),
            (Use, 1, "yssbi_lib::math::ir::UnaryOp"),
            (Use, 1, "yssbi_lib::math::parse_relations"),
            (Path, 1, "yssbi_lib::math::ir::MathError"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/sci/models/regression.rs",
        "yssbi_lib::sci::models::regression",
        [(
            Path,
            1,
            "yssbi_lib::project::computation_settings::StatisticalMissingValuePolicy"
        )],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/kernels/distribution/mod.rs",
        "yssbi_lib::node_system::runtime::kernels::distribution",
        [(Use, 1, "yssbi_lib::node_system::protocol::value::Value"),],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/kernels/mod.rs",
        "yssbi_lib::node_system::runtime::kernels",
        [(Use, 1, "yssbi_lib::node_system::plan::model::KernelHandle"),],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/kernels/plot/mod.rs",
        "yssbi_lib::node_system::runtime::kernels::plot",
        [
            (Use, 1, "yssbi_lib::node_system::plan::model::ResourceId"),
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
            (
                Use,
                1,
                "yssbi_lib::sci::api::time_series::acf_pacf::AcfPacfInput"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::time_series::acf_pacf::compute_acf_pacf"
            ),
            (Use, 1, "yssbi_lib::sci::engine::SciContext"),
            (Path, 1, "yssbi_lib::sci::kde::gaussian_kde_grid"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/kernels/statistics/mod.rs",
        "yssbi_lib::node_system::runtime::kernels::statistics",
        [
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
            (
                Use,
                1,
                "yssbi_lib::project::computation_settings::NumericTolerance"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::computation_settings::StatisticalMissingValuePolicy"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::node_statistics::RegressionKind"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::models::regression::StatisticalObservationMetadata"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::models::regression::StatisticalSettingSource"
            ),
            (
                Path,
                1,
                "yssbi_lib::sci::api::node_statistics::InstrumentalVariableKind::LimitedInformationMaximumLikelihood"
            ),
            (
                Path,
                1,
                "yssbi_lib::sci::api::node_statistics::InstrumentalVariableKind::TwoStageLeastSquares"
            ),
            (
                Path,
                2,
                "yssbi_lib::sci::api::node_statistics::RegressionFit"
            ),
            (
                Path,
                1,
                "yssbi_lib::sci::api::node_statistics::RegressionKind"
            ),
            (
                Path,
                1,
                "yssbi_lib::sci::api::node_statistics::augmented_dickey_fuller"
            ),
            (
                Path,
                1,
                "yssbi_lib::sci::api::node_statistics::fit_instrumental_variables"
            ),
            (Path, 1, "yssbi_lib::sci::api::node_statistics::fit_panel"),
            (
                Path,
                1,
                "yssbi_lib::sci::api::node_statistics::fit_regression"
            ),
            (
                Path,
                1,
                "yssbi_lib::sci::api::node_statistics::regression_report"
            ),
            (Path, 1, "yssbi_lib::sci::api::node_statistics::var_fit"),
            (
                Path,
                1,
                "yssbi_lib::sci::api::node_statistics::var_lag_order"
            ),
            (Path, 1, "yssbi_lib::sci::api::node_statistics::vec_fit"),
            (
                Path,
                1,
                "yssbi_lib::sci::api::node_statistics::vec_rank_test"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/materialization.rs",
        "yssbi_lib::node_system::runtime::materialization",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::MaterializationLimits"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::PlannedAdapter"
            ),
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/memoization.rs",
        "yssbi_lib::node_system::runtime::memoization",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceVersionSet"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::CallArgumentBinding"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::CallResultBinding"
            ),
            (Use, 1, "yssbi_lib::node_system::plan::model::ExecutionPlan"),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::ExecutionSemanticsVersion"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::FunctionPlanHandle"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::OperationStableId"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::registry::fingerprint::hash_canonical"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/mod.rs",
        "yssbi_lib::node_system::runtime",
        [
            (
                ReExport,
                1,
                "yssbi_lib::node_system::runtime::builtin::BuiltinConstantParameters"
            ),
            (
                ReExport,
                1,
                "yssbi_lib::node_system::runtime::builtin::BuiltinVariableParameters"
            ),
            (
                ReExport,
                1,
                "yssbi_lib::node_system::runtime::builtin::build_builtin_kernel_registry"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/numeric.rs",
        "yssbi_lib::node_system::runtime::numeric",
        [
            (
                Use,
                1,
                "yssbi_lib::project::computation_settings::NumericTolerance"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::computation_settings::StatisticalMissingValuePolicy"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/parameters.rs",
        "yssbi_lib::node_system::runtime::parameters",
        [(
            Use,
            1,
            "yssbi_lib::node_system::plan::model::CompiledParameterHandle"
        ),],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/production_relational.rs",
        "yssbi_lib::node_system::runtime::production_relational",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::CompiledRelationalPlan"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::RelationalOperator"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::RelationalOperatorIndex"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::infer_relational_pushdown_hints"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::plan::model::RelationalPushdownHint::Limit"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/project_resource.rs",
        "yssbi_lib::node_system::runtime::project_resource",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceKey"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceVersion"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceVersionSet"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::provenance::CompileProvenance"
            ),
            (Use, 1, "yssbi_lib::node_system::identity::ProjectSessionId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::CompiledResourceRequirement"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::ResourceAccess"
            ),
            (Use, 1, "yssbi_lib::node_system::plan::model::ResourceId"),
            (Use, 1, "yssbi_lib::node_system::plan::model::ResourceKind"),
            (
                Path,
                1,
                "yssbi_lib::database::duckdb_reader::duckdb_table_sql"
            ),
            (
                Path,
                1,
                "yssbi_lib::database::duckdb_reader::query_to_dataframe_for_table"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::document::ids::ResourceRevision"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::ids::ResourceRevision::INITIAL"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/project_run.rs",
        "yssbi_lib::node_system::runtime::project_run",
        [
            (Use, 1, "yssbi_lib::node_system::identity::ProjectSessionId"),
            (
                Path,
                1,
                "yssbi_lib::node_system::id_allocator::allocate_nonzero_id"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/relational.rs",
        "yssbi_lib::node_system::runtime::relational",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::CompiledRelationalPlan"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::RelationalBackendId"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::RelationalSubplan"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/relational_dataframe.rs",
        "yssbi_lib::node_system::runtime::relational_dataframe",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::RelationalExpression"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::RelationalLiteral"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::RelationalProjection"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::RelationalRename"
            ),
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/resource.rs",
        "yssbi_lib::node_system::runtime::resource",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::provenance::CompileProvenance"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::CompiledResourceRequirement"
            ),
            (Use, 1, "yssbi_lib::node_system::plan::model::ResourceId"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/result.rs",
        "yssbi_lib::node_system::runtime::result",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::document::ids::GraphRevision"
            ),
            (Use, 1, "yssbi_lib::node_system::document::ids::NodeId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::model::GraphResourcePath"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::GraphOutputRef"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::PlannedValueContract"
            ),
            (Use, 1, "yssbi_lib::node_system::plan::model::ValueRef"),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::result_presentation::ResultPresentation"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/result_store.rs",
        "yssbi_lib::node_system::runtime::result_store",
        [
            (
                Path,
                7,
                "yssbi_lib::node_system::plan::model::GraphOutputRef"
            ),
            (Path, 1, "yssbi_lib::node_system::plan::model::ValueRef"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/run.rs",
        "yssbi_lib::node_system::runtime::run",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::provenance::CompileProvenance"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::OperationIndex"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::RelationalBackendId"
            ),
            (Use, 1, "yssbi_lib::node_system::plan::model::ResourceId"),
            (Use, 1, "yssbi_lib::node_system::plan::model::ValueRef"),
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
            (
                Path,
                1,
                "yssbi_lib::node_system::id_allocator::allocate_nonzero_id"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/run_output.rs",
        "yssbi_lib::node_system::runtime::run_output",
        [
            (Use, 1, "yssbi_lib::node_system::document::ids::NodeId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::model::GraphResourcePath"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/scheduler.rs",
        "yssbi_lib::node_system::runtime::scheduler",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceVersionSet"
            ),
            (Use, 1, "yssbi_lib::node_system::plan::model::AttemptId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::CallArgumentBinding"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::CallResultBinding"
            ),
            (Use, 1, "yssbi_lib::node_system::plan::model::ControlStep"),
            (Use, 1, "yssbi_lib::node_system::plan::model::ExecutionPlan"),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::FunctionPlanHandle"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::OperationIndex"
            ),
            (Use, 1, "yssbi_lib::node_system::plan::model::PlannedKernel"),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::PlannedPublication"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::PlannedValueContract"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::PlannedValueKind"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::StructuredControlRegion"
            ),
            (Use, 1, "yssbi_lib::node_system::plan::model::ValueRef"),
            (Use, 1, "yssbi_lib::node_system::plan::model::WorkloadClass"),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::result_presentation::ResultPresentation"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::protocol::model::CachePolicy"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::protocol::model::RetryPolicy"
            ),
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
            (Path, 2, "yssbi_lib::node_system::document::ids::NodeId"),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::ids::NodeId::from_uuid"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::id_allocator::allocate_nonzero_id"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::computation_settings::ProjectComputationSettings"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/scheduling.rs",
        "yssbi_lib::node_system::runtime::scheduling",
        [
            (Use, 1, "yssbi_lib::node_system::plan::model::AttemptId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::OperationIndex"
            ),
            (Use, 1, "yssbi_lib::node_system::plan::model::WorkloadClass"),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/spill.rs",
        "yssbi_lib::node_system::runtime::spill",
        [(Use, 1, "yssbi_lib::node_system::protocol::value::Value"),],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/stored_value.rs",
        "yssbi_lib::node_system::runtime::stored_value",
        [
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
            (
                Path,
                4,
                "yssbi_lib::node_system::registry::fingerprint::hash_canonical"
            ),
        ],
    );
    debt_group!(
        entries,
        EXECUTION_RUNTIME_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_lifecycle.rs",
        "yssbi_lib::project::project_lifecycle",
        [(
            Path,
            1,
            "yssbi_lib::node_system::runtime::project_run::ProjectRunDrainGuard"
        ),],
    );
}
