use crate::architecture_tests::model::RustDebtEntry;

use super::PRESENTATION_COMMAND_SPEC;

pub(super) fn extend(entries: &mut Vec<RustDebtEntry>) {
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/commands/command_bayes.rs",
        "yssbi_lib::commands::command_bayes",
        [
            (Use, 1, "external:serde::Deserialize"),
            (Use, 1, "external:serde::Serialize"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/commands/command_dataframe/error.rs",
        "yssbi_lib::commands::command_dataframe::error",
        [(Use, 1, "external:serde::Serialize"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/commands/command_dataframe/mod.rs",
        "yssbi_lib::commands::command_dataframe",
        [(Path, 2, "external:serde::Serialize"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/commands/command_dataframe/types.rs",
        "yssbi_lib::commands::command_dataframe::types",
        [
            (Use, 1, "external:chrono::DateTime"),
            (Use, 1, "external:chrono::Datelike"),
            (Use, 1, "external:chrono::NaiveDate"),
            (Use, 1, "external:polars::prelude::AnyValue"),
            (Use, 1, "external:polars::prelude::DataFrame"),
            (Use, 1, "external:polars::prelude::TimeUnit"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/commands/command_hypothesis.rs",
        "yssbi_lib::commands::command_hypothesis",
        [
            (Use, 1, "external:serde::Deserialize"),
            (Use, 1, "external:serde::Serialize"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/commands/command_node_system/common.rs",
        "yssbi_lib::commands::command_node_system::common",
        [(Use, 1, "external:serde::Serialize"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/commands/command_node_system/execution.rs",
        "yssbi_lib::commands::command_node_system::execution",
        [(Use, 1, "external:serde::Serialize"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/commands/command_node_system/results.rs",
        "yssbi_lib::commands::command_node_system::results",
        [(Use, 1, "external:serde::Serialize"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/commands/command_parse_at.rs",
        "yssbi_lib::commands::command_parse_at",
        [
            (Use, 1, "external:serde::Deserialize"),
            (Use, 1, "external:serde::Serialize"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/commands/command_variable/mod.rs",
        "yssbi_lib::commands::command_variable",
        [(Path, 1, "external:serde::Serialize"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/commands/command_worksheet.rs",
        "yssbi_lib::commands::command_worksheet",
        [
            (Use, 1, "external:polars::prelude::DataType"),
            (Use, 1, "external:polars::prelude::Series"),
            (Use, 1, "external:serde::Serialize"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/commands/node_system_execution_dto.rs",
        "yssbi_lib::commands::node_system_execution_dto",
        [
            (Use, 1, "external:serde::Deserialize"),
            (Use, 1, "external:serde::Serialize"),
            (Use, 1, "external:serde::Serializer"),
            (Use, 1, "external:serde::ser::SerializeMap"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/diagnostics/dispatcher.rs",
        "yssbi_lib::diagnostics::dispatcher",
        [(Use, 1, "external:uuid::Uuid"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/diagnostics/dto.rs",
        "yssbi_lib::diagnostics::dto",
        [
            (Use, 1, "external:serde::Deserialize"),
            (Use, 1, "external:serde::Serialize"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/diagnostics/runtime.rs",
        "yssbi_lib::diagnostics::runtime",
        [(Use, 1, "external:tauri::ipc::Channel"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.external.runtime-source-layer",
        "src-tauri/src/diagnostics/sanitizer.rs",
        "yssbi_lib::diagnostics::sanitizer",
        [(Use, 1, "external:regex::Regex"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/application/bayes.rs",
        "yssbi_lib::application::bayes",
        [(Use, 1, "yssbi_lib::error::new_diagnostic_incident_id"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/application/database.rs",
        "yssbi_lib::application::database",
        [
            (Use, 1, "yssbi_lib::schema::database::ColumnInfoDTO"),
            (Use, 1, "yssbi_lib::schema::database::DatabaseEngineDTO"),
            (
                Use,
                1,
                "yssbi_lib::schema::database::column_info_from_duckdb"
            ),
            (
                Path,
                11,
                "yssbi_lib::event::event_project::ResourceMutationCommandResultDto"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/application/database_schema.rs",
        "yssbi_lib::application::database_schema",
        [
            (Use, 1, "yssbi_lib::schema::database::ColumnInfoDTO"),
            (Use, 1, "yssbi_lib::schema::database::DatabaseDeclDTO"),
            (
                Use,
                1,
                "yssbi_lib::schema::database::column_info_from_duckdb"
            ),
            (
                Use,
                1,
                "yssbi_lib::schema::database::column_info_from_schema"
            ),
            (Use, 1, "yssbi_lib::schema::project::DatabasesVariablesDTO"),
            (Use, 1, "yssbi_lib::schema::variables::VariableInstanceDTO"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/application/graph_execution.rs",
        "yssbi_lib::application::graph_execution",
        [(
            Use,
            1,
            "yssbi_lib::event::event_project::ResourceMutationResultDto"
        ),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/application/project_lifecycle/mod.rs",
        "yssbi_lib::application::project_lifecycle",
        [
            (
                Use,
                1,
                "yssbi_lib::event::event_project::LifecycleInvalidationDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::event::event_project::LifecycleMutationKindDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::event::event_project::LifecycleMutationOutcomeDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::event::event_project::LifecycleMutationPhaseDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::event::event_project::LifecycleMutationResultDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::event::event_project::LifecycleRecoveryDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::event::event_project::ProjectActivationResultDto"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_bayes.rs",
        "yssbi_lib::commands::command_bayes",
        [
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
            (Use, 1, "yssbi_lib::sci::api::bayes::draft::BayesModelDraft"),
            (Use, 1, "yssbi_lib::sci::api::bayes::draft::ColumnMeta"),
            (
                Use,
                1,
                "yssbi_lib::sci::api::bayes::expression::ParsedExpression"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::bayes::expression::parse_model_expression"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::bayes::result::AutocorrelationPlotData"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::bayes::result::BayesInferenceTask"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::bayes::result::DensityPlotData"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::bayes::result::InferenceResult"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::bayes::result::PosteriorPredictivePage"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::bayes::result::PosteriorSamplePage"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::bayes::result::ResultArtifactKind"
            ),
            (Use, 1, "yssbi_lib::sci::api::bayes::result::TracePlotData"),
            (
                Use,
                1,
                "yssbi_lib::sci::api::bayes::validators::validate_draft"
            ),
            (Path, 1, "yssbi_lib::math::ParseOptions::latex"),
            (Path, 1, "yssbi_lib::math::ParseOptions::plain"),
            (
                Path,
                1,
                "yssbi_lib::sci::api::bayes::validation::ValidationReport"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_dataframe/error.rs",
        "yssbi_lib::commands::command_dataframe::error",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::document::ids::ResourceRevision"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_dataframe/mod.rs",
        "yssbi_lib::commands::command_dataframe",
        [
            (Use, 1, "yssbi_lib::application::database"),
            (Use, 1, "yssbi_lib::node_system::document::ids::OperationId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::ids::ResourceRevision"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
            (Path, 12, "yssbi_lib::database::edit_operation::EditState"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_julia.rs",
        "yssbi_lib::commands::command_julia",
        [
            (Use, 1, "yssbi_lib::julia::JuliaRuntimeStatus"),
            (Use, 1, "yssbi_lib::julia::get_runtime_status"),
            (Use, 1, "yssbi_lib::julia::install_latest_julia"),
            (Use, 1, "yssbi_lib::julia::worker::JuliaWorkerManager"),
            (Use, 1, "yssbi_lib::julia::worker::JuliaWorkerStatus"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_node_system/catalog.rs",
        "yssbi_lib::commands::command_node_system::catalog",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::localization::LocalizedCatalogDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::ids::ResourceRevision"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::PortAddressDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_error::ProjectFilesystemError"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_node_system/common.rs",
        "yssbi_lib::commands::command_node_system::common",
        [
            (
                Use,
                1,
                "yssbi_lib::project::graph_resource_path::GraphResourcePath"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::error::DocumentError::ConnectionNotFound"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::mutation::MutationConflict"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::mutation::MutationConflict::CatalogDescriptorInvalid"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::mutation::MutationConflict::CatalogResourceStale"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::mutation::MutationConflict::ClipboardSubgraphInvalid"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::mutation::MutationConflict::Document"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::mutation::MutationConflict::Editor"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::mutation::MutationConflict::RecoveryRequired"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::mutation::MutationConflict::ReferencedResourceUnavailable"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::mutation::MutationConflict::StaleProjectLifecycle"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::mutation::MutationConflict::StaleRevision"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_node_system/editor.rs",
        "yssbi_lib::commands::command_node_system::editor",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::projection::types::EditorGraphProjectionDto"
            ),
            (Use, 1, "yssbi_lib::node_system::document::ids::NodeId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::EditorGraphMutationDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::MutationRequest"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::subgraph::clipboard::ClipboardSubgraphDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::catalog::localization::NodeCreationDescriptor"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_node_system/execution.rs",
        "yssbi_lib::commands::command_node_system::execution",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::execution_event::RunErrorCode"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::errors::ProjectExecutionErrorKind"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::pipeline::CompilationStage::Analysis"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::pipeline::CompilationStage::Lowering"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::plan::model::ExecutionDemand::try_from"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::execution_event::RunErrorCode"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::execution_event::RunErrorCode::from"
            ),
            (Path, 1, "yssbi_lib::node_system::runtime::run::RunId::new"),
            (
                Path,
                1,
                "yssbi_lib::project::project_state::errors::ProjectExecutionError"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_node_system/history.rs",
        "yssbi_lib::commands::command_node_system::history",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::HistoryMutation"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::HistoryStatusDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::MutationRequest"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_node_system/resources.rs",
        "yssbi_lib::commands::command_node_system::resources",
        [
            (Use, 1, "yssbi_lib::node_system::document::ids::OperationId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::ids::ResourceRevision"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::MutationRequest"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::graph_resource_path::GraphResourcePath"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_writers::ProjectSaveResultDto"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::FunctionDocumentPatch"
            ),
            (Path, 1, "yssbi_lib::project::project_io::GraphDocumentKind"),
            (
                Path,
                1,
                "yssbi_lib::project::project_io::GraphDocumentKind::Event"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::project_io::GraphDocumentKind::Function"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId::from_existing"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_node_system/results.rs",
        "yssbi_lib::commands::command_node_system::results",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::PortAddressDto"
            ),
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
            (Use, 1, "yssbi_lib::node_system::runtime::result::ResultId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::result::ResultState"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::stored_value::StoredValueKind"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::model::GraphResourcePath"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::plan::model::GraphOutputRef"
            ),
            (Path, 2, "yssbi_lib::node_system::protocol::value::Value"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_panel_did.rs",
        "yssbi_lib::commands::command_panel_did",
        [
            (
                Use,
                1,
                "yssbi_lib::sci::models::panel_did::ComputeDidFakeGroupRequest"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::models::panel_did::DidPlaceboFakeGroupBlock"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::models::panel_did::compute_fake_group_ri"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_project/lifecycle.rs",
        "yssbi_lib::commands::command_project::lifecycle",
        [
            (Use, 1, "yssbi_lib::application::project_lifecycle"),
            (Use, 1, "yssbi_lib::node_system::document::ids::OperationId"),
            (
                Use,
                1,
                "yssbi_lib::project::project_registry::ProjectRegistry"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_watcher::ProjectWatcherState"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_writers::ProjectSaveResultDto"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_project/path.rs",
        "yssbi_lib::commands::command_project::path",
        [
            (
                Use,
                1,
                "yssbi_lib::project::project_registry::default_project_parent_directory"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_registry::validate_new_project_path"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_project/query.rs",
        "yssbi_lib::commands::command_project::query",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::projection::types::EditorGraphProjectionDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::path_format::format_path_for_user_path"
            ),
            (Use, 1, "yssbi_lib::project::project_io::ProjectIndex"),
            (
                Use,
                1,
                "yssbi_lib::project::project_registry::normalize_existing_path"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::resource_reveal::RevealProjectResourceRequest"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::resource_reveal::resolve_reveal_path"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::graph_resource_path::GraphResourcePath::new"
            ),
            (
                Path,
                2,
                "yssbi_lib::project::project_session::ProjectInstanceId::from_existing"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_project/registry.rs",
        "yssbi_lib::commands::command_project::registry",
        [
            (Use, 1, "yssbi_lib::node_system::document::ids::OperationId"),
            (
                Use,
                1,
                "yssbi_lib::project::project_picker_task::ProjectPickerTaskCancelRegistry"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_registry::CleanupInvalidProjectsResult"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_registry::ProjectRecord"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_registry::ProjectRegistry"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_scan::ScanProjectsResult"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::project_picker_task::ProjectCleanupProgressEvent"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::project_scan::ProjectScanProgressEvent"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_project/settings.rs",
        "yssbi_lib::commands::command_project::settings",
        [
            (
                Use,
                1,
                "yssbi_lib::project::computation_settings::ComputationSettingsMutationReceipt"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::computation_settings::ComputationSettingsMutationRequest"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::computation_settings::ComputationSettingsSnapshot"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_sci.rs",
        "yssbi_lib::commands::command_sci",
        [
            (
                Use,
                1,
                "yssbi_lib::sci::api::time_series::acf_pacf::AcfPacfInput"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::time_series::acf_pacf::AcfPacfOutput"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::time_series::acf_pacf::compute_acf_pacf"
            ),
            (Use, 1, "yssbi_lib::sci::engine::SciContext"),
            (Use, 1, "yssbi_lib::sci::error::SciError"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_serial_tests.rs",
        "yssbi_lib::commands::command_serial_tests",
        [
            (
                Use,
                1,
                "yssbi_lib::sci::api::time_series::serial_tests::SerialTestsInput"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::time_series::serial_tests::SerialTestsOutput"
            ),
            (
                Use,
                1,
                "yssbi_lib::sci::api::time_series::serial_tests::compute_serial_tests"
            ),
            (Use, 1, "yssbi_lib::sci::engine::SciContext"),
            (Use, 1, "yssbi_lib::sci::error::SciError"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_variable/mod.rs",
        "yssbi_lib::commands::command_variable",
        [
            (Use, 1, "yssbi_lib::node_system::document::ids::OperationId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::ids::ResourceRevision"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/command_worksheet.rs",
        "yssbi_lib::commands::command_worksheet",
        [
            (
                Use,
                1,
                "yssbi_lib::database::database_instance::DatabaseInstance"
            ),
            (Use, 1, "yssbi_lib::node_system::document::ids::OperationId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::ids::ResourceRevision"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_error::ProjectFilesystemError"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_state::state::ProjectState"
            ),
            (Use, 1, "yssbi_lib::project::resource_name::ResourceName"),
            (
                Use,
                1,
                "yssbi_lib::project::worksheet_io::WorksheetDocument"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::worksheet_resource_path::WorksheetResourcePath"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::project_session::ProjectInstanceId::from_existing"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/commands/node_system_execution_dto.rs",
        "yssbi_lib::commands::node_system_execution_dto",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::document::model::GraphResourcePath"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::PortAddressDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::ExecutionDemand"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::GraphOutputRef"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::MAX_SAFE_PREVIEW_GENERATION"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::PlannedValueKind"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::result_presentation::ResultPresentation"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::data_series::DataSeriesMetadata"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::execution_event::GraphRunIdentity"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::execution_event::OrdinaryRunErrorCode"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::execution_event::RunErrorCode"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::execution_event::RunErrorOutcome"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::execution_event::RunEvent"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::execution_event::RunEventKind"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::result::PinResultEntry"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::result::ResultFailureCause"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::result::ResultState"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::result::ResultUsage"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::result::StoredResult"
            ),
            (Use, 1, "yssbi_lib::node_system::runtime::run::RunPhase"),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::run_output::RunOutputEvent"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::run_output::RunOutputMessage"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::run_output::RunOutputStatus"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::run_output::RunOutputStatusEvent"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::run_output::RunOutputStream"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::stored_value::StoredValueKind"
            ),
            (Path, 1, "yssbi_lib::node_system::runtime::result::ResultId"),
            (
                Path,
                2,
                "yssbi_lib::node_system::runtime::result::ResultStateKind"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::result::ResultStateKind::Cancelled"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::result::ResultStateKind::Failed"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::result::ResultStateKind::Pending"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::result::ResultStateKind::Ready"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/lib.rs",
        "yssbi_lib",
        [(Use, 1, "yssbi_lib::commands::*"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/analysis/basis.rs",
        "yssbi_lib::node_system::analysis::basis",
        [(Path, 1, "yssbi_lib::schema::database::ColumnInfoDTO"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/compiler/pipeline/resource_snapshot.rs",
        "yssbi_lib::node_system::compiler::pipeline::resource_snapshot",
        [(Path, 1, "yssbi_lib::schema::database::ColumnInfoDTO"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/compile_resources.rs",
        "yssbi_lib::project::project_state::compile_resources",
        [(Path, 3, "yssbi_lib::schema::database::ColumnInfoDTO"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/editor_mutation.rs",
        "yssbi_lib::project::project_state::editor_mutation",
        [(
            Path,
            1,
            "yssbi_lib::event::event_project::GraphProjectionReplacementDto"
        ),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/execution.rs",
        "yssbi_lib::project::project_state::execution",
        [(Path, 1, "yssbi_lib::schema::database::ColumnInfoDTO"),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/graph_rename.rs",
        "yssbi_lib::project::project_state::graph_lifecycle::graph_rename",
        [(
            Path,
            1,
            "yssbi_lib::event::event_project::ResourceMutationResultDto"
        ),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/history.rs",
        "yssbi_lib::project::project_state::history",
        [(
            Path,
            6,
            "yssbi_lib::event::event_project::ResourceMutationResultDto"
        ),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/projection.rs",
        "yssbi_lib::project::project_state::projection",
        [
            (
                Path,
                4,
                "yssbi_lib::event::event_project::GraphProjectionReplacementDto"
            ),
            (Path, 1, "yssbi_lib::schema::database::ColumnInfoDTO"),
            (
                Path,
                2,
                "yssbi_lib::schema::database::column_info_from_duckdb"
            ),
            (
                Path,
                1,
                "yssbi_lib::schema::database::column_info_from_schema"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/resource_patch.rs",
        "yssbi_lib::project::project_state::resource_patch",
        [
            (
                Path,
                1,
                "yssbi_lib::event::event_project::ProjectionStatusDto::Complete"
            ),
            (
                Path,
                1,
                "yssbi_lib::event::event_project::ProjectionStatusDto::Incomplete"
            ),
            (Path, 3, "yssbi_lib::event::event_project::ResourceMoveDto"),
            (
                Path,
                5,
                "yssbi_lib::event::event_project::ResourceMutationResultDto"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/variable_effects.rs",
        "yssbi_lib::project::project_state::variable_effects",
        [(
            Path,
            1,
            "yssbi_lib::event::event_project::ResourceMutationResultDto"
        ),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state_database.rs",
        "yssbi_lib::project::project_state_database",
        [
            (
                Path,
                1,
                "yssbi_lib::event::event_project::ProjectionStatusDto::Complete"
            ),
            (
                Path,
                4,
                "yssbi_lib::event::event_project::ResourceMutationCommandResultDto"
            ),
            (
                Path,
                6,
                "yssbi_lib::event::event_project::ResourceMutationResultDto"
            ),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_watcher.rs",
        "yssbi_lib::project::project_watcher",
        [
            (Use, 1, "yssbi_lib::event::Event"),
            (Use, 1, "yssbi_lib::event::emit_project_event"),
            (Use, 1, "yssbi_lib::event::event_resource::EventResource"),
        ],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_writers.rs",
        "yssbi_lib::project::project_writers",
        [(
            Use,
            1,
            "yssbi_lib::event::event_project::ResourceMutationResultDto"
        ),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_writers/variables.rs",
        "yssbi_lib::project::project_writers::variables",
        [(
            Path,
            1,
            "yssbi_lib::event::event_project::ProjectionStatusDto::Complete"
        ),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/resource_mutations/graph_operations.rs",
        "yssbi_lib::project::resource_mutations::graph_operations",
        [(
            Path,
            3,
            "yssbi_lib::event::event_project::ResourceMutationResultDto"
        ),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/resource_mutations/rename_operations.rs",
        "yssbi_lib::project::resource_mutations::rename_operations",
        [(
            Path,
            1,
            "yssbi_lib::event::event_project::ResourceMutationResultDto"
        ),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/runtime/run.rs",
        "yssbi_lib::node_system::runtime::run",
        [(
            Path,
            1,
            "yssbi_lib::event::event_project::ResourceMutationResultDto"
        ),],
    );
    debt_group!(
        entries,
        PRESENTATION_COMMAND_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state.rs",
        "yssbi_lib::project::project_state",
        [(
            Use,
            1,
            "yssbi_lib::event::event_project::GraphMutationResultDto"
        ),],
    );
}
