use crate::architecture_tests::model::RustDebtEntry;

use super::PROJECT_GRAPH_SPEC;

pub(super) fn extend(entries: &mut Vec<RustDebtEntry>) {
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/analysis/projection/graph_builder.rs",
        "yssbi_lib::node_system::analysis::projection::graph_builder",
        [
            (
                Path,
                1,
                "yssbi_lib::project::computation_settings::ProjectComputationSettings"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::computation_settings::ProjectComputationSettings::default"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/analysis/projection/parameter_editors.rs",
        "yssbi_lib::node_system::analysis::projection::parameter_editors",
        [
            (
                Path,
                1,
                "yssbi_lib::project::computation_settings::ProjectComputationSettings"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::computation_settings::StatisticalMissingValuePolicy::Listwise"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::computation_settings::StatisticalMissingValuePolicy::Reject"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/catalog/control.rs",
        "yssbi_lib::node_system::catalog::control",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinAssemblyError"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_interface"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_parameters"
            ),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::iid"),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::sid"),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/catalog/core_nodes/mod.rs",
        "yssbi_lib::node_system::catalog::core_nodes",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinAssemblyError"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::ProviderFragment"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/catalog/core_nodes/reroute.rs",
        "yssbi_lib::node_system::catalog::core_nodes::reroute",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinAssemblyError"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::ProviderFragment"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/catalog/core_nodes/support.rs",
        "yssbi_lib::node_system::catalog::core_nodes::support",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinAssemblyError"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::ProviderFragment"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_decimal"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_interface"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_parameters"
            ),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::sid"),
            (
                Path,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinAssemblyError"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/catalog/dataframe/mod.rs",
        "yssbi_lib::node_system::catalog::dataframe",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinAssemblyError"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::ProviderFragment"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_interface"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_parameters"
            ),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::iid"),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::leaf"),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::sid"),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/catalog/distribution/mod.rs",
        "yssbi_lib::node_system::catalog::distribution",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinAssemblyError"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::ProviderFragment"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_interface"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_parameters"
            ),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::sid"),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/catalog/mod.rs",
        "yssbi_lib::node_system::catalog",
        [
            (
                ReExport,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinAssemblyError"
            ),
            (
                ReExport,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinInitializationError"
            ),
            (
                ReExport,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinNodeSystem"
            ),
            (
                ReExport,
                1,
                "yssbi_lib::node_system::catalog::builtin::build_builtin_node_system"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/catalog/plot/mod.rs",
        "yssbi_lib::node_system::catalog::plot",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinAssemblyError"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::ProviderFragment"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_interface"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_parameters"
            ),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::sid"),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/catalog/project.rs",
        "yssbi_lib::node_system::catalog::project",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinAssemblyError"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_interface"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_parameters"
            ),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::iid"),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::leaf"),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::sid"),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/catalog/statistics/mod.rs",
        "yssbi_lib::node_system::catalog::statistics",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinAssemblyError"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::ProviderFragment"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_decimal"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_interface"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::assembled_parameters"
            ),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::iid"),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::leaf"),
            (Use, 1, "yssbi_lib::node_system::catalog::builtin::sid"),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/compatibility.rs",
        "yssbi_lib::node_system::compatibility",
        [
            (
                Use,
                1,
                "yssbi_lib::project::project_reads::CatalogMutationResource"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_reads::CatalogMutationValidationSnapshot"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::project_reads::CatalogProjectSnapshot"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/document/history.rs",
        "yssbi_lib::node_system::document::history",
        [
            (
                Use,
                1,
                "yssbi_lib::project::worksheet_io::WorksheetDocument"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::worksheet_io::WorksheetEncodings"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/document/mutation.rs",
        "yssbi_lib::node_system::document::mutation",
        [
            (
                Path,
                1,
                "yssbi_lib::project::project_reads::CatalogMutationResource::Database"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::project_reads::CatalogMutationResource::Function"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::project_reads::CatalogMutationResource::Variable"
            ),
            (
                Path,
                5,
                "yssbi_lib::project::project_reads::CatalogMutationValidationSnapshot"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/document/mutation/connection.rs",
        "yssbi_lib::node_system::document::mutation::connection",
        [
            (
                Path,
                1,
                "yssbi_lib::project::project_reads::CatalogMutationResource::Database"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::project_reads::CatalogMutationResource::Function"
            ),
            (
                Path,
                1,
                "yssbi_lib::project::project_reads::CatalogMutationValidationSnapshot"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/document/subgraph.rs",
        "yssbi_lib::node_system::document::subgraph",
        [
            (
                Use,
                1,
                "yssbi_lib::project::project_reads::CatalogMutationResource"
            ),
            (
                Use,
                1,
                "yssbi_lib::project::project_reads::CatalogMutationValidationSnapshot"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/document/subgraph/instantiate.rs",
        "yssbi_lib::node_system::document::subgraph::instantiate",
        [],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/activation.rs",
        "yssbi_lib::project::project_state::activation",
        [(
            Path,
            1,
            "yssbi_lib::node_system::compiler::ProjectCompileCoordinator::new"
        ),],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/authority.rs",
        "yssbi_lib::project::project_state::authority",
        [],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/compile_resources.rs",
        "yssbi_lib::project::project_state::compile_resources",
        [
            (
                Use,
                2,
                "yssbi_lib::node_system::analysis::basis::ResourceKey"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceObservedState"
            ),
            (
                Use,
                2,
                "yssbi_lib::node_system::analysis::basis::ResourceVersion"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::analysis::basis::ResourceKey"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceObservationSet"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceObservedState"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceObservedState::Absent"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceObservedState::Present"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceVersion"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::analysis::basis::ResourceVersionSet"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceVersionSet::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::catalog::dataframe::DATAFRAME_RESOURCE_SCHEMA_RESOLVER"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::schema_analysis::SchemaFact"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::schema_analysis::SchemaFact::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::schema_analysis::SchemaResolutionContext"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::schema_analysis::SchemaResolutionError"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::schema_analysis::SchemaResolutionError::from_resource"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::compiler::schema_analysis::SchemaResolutionError::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::schema_analysis::SchemaResolver"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::schema_analysis::SchemaResolverSet"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::schema_analysis::SchemaResolverSet::new"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::FunctionDocument"
            ),
            (Path, 3, "yssbi_lib::node_system::plan::model::ResourceId"),
            (
                Path,
                4,
                "yssbi_lib::node_system::plan::model::ResourceId::new"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/editor_mutation.rs",
        "yssbi_lib::project::project_state::editor_mutation",
        [
            (
                Path,
                1,
                "yssbi_lib::node_system::catalog::localization::NodeCreationDescriptor::ResourceBound"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compatibility::EditorMutationValidationSnapshot"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compatibility::EditorMutationValidationSnapshot::from_projection"
            ),
            (Path, 1, "yssbi_lib::node_system::compatibility::SourcePort"),
            (
                Path,
                1,
                "yssbi_lib::node_system::compatibility::refine_source_type"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compatibility::source_from_projection"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::mutation::ProjectedConnectPlan"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::registry::model::NodeRegistry"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/errors.rs",
        "yssbi_lib::project::project_state::errors",
        [(
            Path,
            3,
            "yssbi_lib::node_system::compiler::pipeline::InternalCompilationFailure"
        ),],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/execution.rs",
        "yssbi_lib::project::project_state::execution",
        [
            (Use, 1, "yssbi_lib::node_system::plan::model::ResourceId"),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::coordinator::CompileCancellationToken::from_shared"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::pipeline::CompilationOutcome::AnalysisBlocked"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::pipeline::CompilationOutcome::InternalFailure"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::pipeline::CompilationOutcome::Succeeded"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::pipeline::CompilationStage::Lowering"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::pipeline::InternalCompilationFailure"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::identity::ProjectSessionId"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::plan::model::ExecutionDemand"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::plan::model::RelationalBackendId::new"
            ),
            (Path, 1, "yssbi_lib::node_system::plan::model::ResourceId"),
            (
                Path,
                1,
                "yssbi_lib::node_system::registry::model::NodeRegistry"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/graph_load.rs",
        "yssbi_lib::project::project_state::graph_lifecycle::graph_load",
        [],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/graph_rename.rs",
        "yssbi_lib::project::project_state::graph_lifecycle::graph_rename",
        [(
            Path,
            1,
            "yssbi_lib::node_system::document::history::VariableResourceKey"
        ),],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/history.rs",
        "yssbi_lib::project::project_state::history",
        [
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::FunctionDocumentPatch"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::document::history::FunctionResourceKey"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::document::history::HistoryError::HistoryHeadChanged"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::HistoryPersistencePolicy"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::HistoryPersistencePolicy::DurableResourceMove"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::HistoryPersistencePolicy::DurableVariableEffects"
            ),
            (
                Path,
                4,
                "yssbi_lib::node_system::document::history::HistoryPersistencePolicy::InMemoryUntilSave"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ProjectHistoryTransaction::new"
            ),
            (
                Path,
                4,
                "yssbi_lib::node_system::document::history::ResourceDeltaEvent"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch::Function"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch::ResourceLifecycle"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::ResourceLifecycleHistoryPayload::Worksheet"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceMoveHistoryPayload::Graph"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceMoveHistoryPayload::Worksheet"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourcePatch::function"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::VariableDocument"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::VariableResourceKey"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::WorksheetResourceKey"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/history_moves.rs",
        "yssbi_lib::project::project_state::history::history_moves",
        [
            (
                Path,
                3,
                "yssbi_lib::node_system::document::history::HistoryError::HistoryHeadChanged"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceDeltaEvent"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceLifecycleKind::Worksheet"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceMoveHistoryPayload::Graph"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceMoveHistoryPayload::Worksheet"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::VariableResourceKey"
            ),
            (
                Path,
                4,
                "yssbi_lib::node_system::document::history::WorksheetResourceKey"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/projection.rs",
        "yssbi_lib::project::project_state::projection",
        [
            (Use, 1, "yssbi_lib::node_system::plan::model::ResourceId"),
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::basis::CompileId::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::projection::function_editor::FunctionEditorProjectionDto"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::analysis::projection::function_editor::build_function_editor_projection"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::catalog::localization::BuiltinCatalog"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::build_builtin_interface_resolvers"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::coordinator::CompileCancellationToken::new"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::identity::ProjectSessionId"
            ),
            (Path, 1, "yssbi_lib::node_system::plan::model::ResourceId"),
            (
                Path,
                1,
                "yssbi_lib::node_system::registry::model::NodeRegistry"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/resource_history.rs",
        "yssbi_lib::project::project_state::resource_history",
        [
            (
                Path,
                10,
                "yssbi_lib::node_system::document::history::ResourceDeltaEvent"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch::ResourceLifecycle"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch::ResourceMove"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch::VariableScopeMove"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch::Worksheet"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceKey::Database"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::ResourceKey::Function"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceKey::Graph"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceKey::Variable"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceKey::Worksheet"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::ResourceLifecycleHistoryPayload::Worksheet"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceLifecycleKind::Event"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceLifecycleKind::Function"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceLifecycleKind::Worksheet"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::document::history::ResourceLifecyclePatch"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::document::history::ResourceLifecycleState"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourcePatch::worksheet"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::document::history::ResourcePathMovePatch"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::VariableResourceKey"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::WorksheetDocumentPatch"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::WorksheetDocumentState"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::WorksheetResourceKey"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/resource_patch.rs",
        "yssbi_lib::project::project_state::resource_patch",
        [
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ProjectHistoryTransaction::graph_move"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ProjectHistoryTransaction::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceDeltaEvent"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch::ResourceLifecycle"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceLifecycleKind::Event"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceLifecycleKind::Function"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceLifecycleKind::Worksheet"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourcePatch"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/run_parameters.rs",
        "yssbi_lib::project::project_state::run_parameters",
        [
            (Use, 1, "yssbi_lib::node_system::plan::model::ControlStep"),
            (
                Use,
                1,
                "yssbi_lib::node_system::plan::model::StructuredControlRegion"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::protocol::value::CanonicalDecimal"
            ),
            (Use, 1, "yssbi_lib::node_system::protocol::value::Value"),
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::basis::CompileId::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceKey::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::build_builtin_interface_resolvers"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::coordinator::CompileCancellationToken"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::pipeline::CompilationOutcome::AnalysisBlocked"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::pipeline::CompilationOutcome::InternalFailure"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::pipeline::CompilationOutcome::Succeeded"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::pipeline::CompilationStage::Lowering"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::pipeline::InternalCompilationFailure"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::identity::ProjectSessionId"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::plan::model::ExecutionPlan"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::plan::model::PlannedValueKind::DataSeries"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::plan::model::ResourceId::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::plan::model::StructuredControlRegion"
            ),
            (Path, 1, "yssbi_lib::node_system::protocol::value::Value"),
            (
                Path,
                1,
                "yssbi_lib::node_system::protocol::value::Value::Null"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::registry::model::NodeRegistry"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::builtin::BuiltinConstantParameters::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::runtime::builtin::BuiltinVariableParameters::new"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/state.rs",
        "yssbi_lib::project::project_state::state",
        [
            (
                Path,
                2,
                "yssbi_lib::node_system::catalog::builtin::BuiltinInitializationError"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::ProjectCompileCoordinator"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::ProjectCompileCoordinator::new"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state/variable_effects.rs",
        "yssbi_lib::project::project_state::variable_effects",
        [
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceDeltaEvent"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceKey"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourcePatch::variable"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::VariableDocumentPatch::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::VariableEffectHistorySnapshots"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::document::history::VariableResourceKey"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::identity::ProjectSessionId"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state_database.rs",
        "yssbi_lib::project::project_state_database",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::DatabaseDocumentPatch"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::DatabaseResourceKey"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ResourceDeltaEvent"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ResourceKey"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::identity::ProjectSessionId"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_store.rs",
        "yssbi_lib::project::project_store",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinInitializationError"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinNodeSystem"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::builtin::build_builtin_node_system"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::localization::BuiltinCatalog"
            ),
            (Use, 1, "yssbi_lib::node_system::identity::ProjectSessionId"),
            (
                Use,
                1,
                "yssbi_lib::node_system::registry::model::NodeRegistry"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::runtime::builtin::build_builtin_kernel_registry"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_writers.rs",
        "yssbi_lib::project::project_writers",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::FunctionResourceKey"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ResourceKey"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::VariableResourceKey"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::WorksheetResourceKey"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::HistoryStatusDto"
            ),
            (
                Path,
                4,
                "yssbi_lib::node_system::document::history::ResourceDeltaEvent"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch::ResourceLifecycle"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch::ResourceMove"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch::Worksheet"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceLifecycleKind::Worksheet"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::ResourceLifecyclePatch"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::ResourceLifecycleState"
            ),
            (
                Path,
                4,
                "yssbi_lib::node_system::document::history::ResourcePatch"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourcePathMovePatch"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::WorksheetDocumentPatch"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::WorksheetDocumentState"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_writers/variables.rs",
        "yssbi_lib::project::project_writers::variables",
        [
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ProjectHistoryTransaction::durable_variable_effects"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceDeltaEvent"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch::Variable"
            ),
            (
                Path,
                6,
                "yssbi_lib::node_system::document::history::ResourcePatch::variable"
            ),
            (
                Path,
                6,
                "yssbi_lib::node_system::document::history::VariableDocumentPatch::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::VariableEffectHistorySnapshots"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/resource_mutations/graph_operations.rs",
        "yssbi_lib::project::resource_mutations::graph_operations",
        [(
            Use,
            1,
            "yssbi_lib::node_system::document::history::ResourceKey"
        ),],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/resource_mutations/operation_ledger.rs",
        "yssbi_lib::project::resource_mutations::operation_ledger",
        [],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/resource_mutations/rename_operations.rs",
        "yssbi_lib::project::resource_mutations::rename_operations",
        [],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/resource_patch.rs",
        "yssbi_lib::project::resource_patch",
        [],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/worksheet_io.rs",
        "yssbi_lib::project::worksheet_io",
        [],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/compile_publication.rs",
        "yssbi_lib::project::compile_publication",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::CompilationBasis"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::CompileProjection"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceObservationSet"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceObservedState"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::basis::ResourceVersion"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::compiler::ProjectCompileCoordinator"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::compiler::coordinator::CompilationTask"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::compiler::coordinator::CompileProducts"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::compiler::coordinator::PublishOutcome"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::compiler::coordinator::PublishedExecutionPlan"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::compiler::coordinator::ScheduleOutcome"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::compiler::coordinator::compilation_basis"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::compiler::pipeline::CompilationOutcome"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::compiler::pipeline::GraphCompiler"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::compiler::pipeline::PublishedCompileAnalysis"
            ),
            (Use, 1, "yssbi_lib::node_system::plan::model::ExecutionPlan"),
            (
                Path,
                1,
                "yssbi_lib::node_system::compiler::build_builtin_interface_resolvers"
            ),
            (
                Path,
                6,
                "yssbi_lib::node_system::identity::ProjectSessionId"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/computation_settings.rs",
        "yssbi_lib::project::computation_settings",
        [],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/history_hydration.rs",
        "yssbi_lib::project::history_hydration",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::HistoryMutation"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ProjectDocumentState"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ProjectHistory"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ProjectHistoryTransaction"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ResourceDocumentPatch"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ResourceKey"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::VariableDocument"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::VariableResourceKey"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::WorksheetResourceKey"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::MutationConflict"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::MutationRequest"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::FunctionResourceKey"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::HistoryPersistencePolicy"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::ResourceLifecycleHistoryPayload::Worksheet"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::document::history::ResourceLifecycleKind::Worksheet"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::ResourcePatch"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_activation.rs",
        "yssbi_lib::project::project_activation",
        [],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_data.rs",
        "yssbi_lib::project::project_data",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::document::error::DocumentError"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::FunctionDocument"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::FunctionSignature"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_error.rs",
        "yssbi_lib::project::project_error",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::document::error::DocumentError"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::catalog::builtin::BuiltinInitializationError"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_io.rs",
        "yssbi_lib::project::project_io",
        [
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::projection::function_editor::FunctionEditorProjectionDto"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::projection::function_editor::build_function_editor_projection"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::catalog::localization::CatalogResourcePath"
            ),
            (
                Path,
                2,
                "yssbi_lib::node_system::catalog::localization::CatalogResourcePath::new"
            ),
            (
                Path,
                3,
                "yssbi_lib::node_system::document::history::FunctionDocument"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::FunctionSignature"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::HistoryStatusDto"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_lifecycle.rs",
        "yssbi_lib::project::project_lifecycle",
        [],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_reads.rs",
        "yssbi_lib::project::project_reads",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::localization::BuiltinCatalog"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::localization::CatalogResourceEntry"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::localization::CatalogResourcePath"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::catalog::localization::ResourceBoundCreateArgsDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::FunctionSignature"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::registry::model::NodeRegistry"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::analysis::projection::function_editor::build_function_editor_projection"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::catalog::localization::CatalogResourcePath::new"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::document::history::HistoryStatusDto"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_session.rs",
        "yssbi_lib::project::project_session",
        [(
            Use,
            1,
            "yssbi_lib::node_system::document::history::ResourceKey"
        ),],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/project/project_state.rs",
        "yssbi_lib::project::project_state",
        [
            (
                Use,
                1,
                "yssbi_lib::node_system::analysis::projection::types::EditorGraphProjectionDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::compiler::pipeline::GraphCompiler"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::compiler::pipeline::resource_snapshot::ResourceSnapshot"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::HistoryMutation"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::HistoryStatusDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ProjectDocumentState"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ProjectHistory"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ProjectHistoryTransaction"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::history::ResourceKey"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::EditorGraphMutationDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::GraphDeltaEvent"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::MutationConflict"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::mutation::MutationRequest"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::patch::GraphDocumentPatch"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::subgraph::clipboard::ClipboardSubgraphDto"
            ),
            (
                Use,
                1,
                "yssbi_lib::node_system::document::subgraph::export_subgraph"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::catalog::localization::LocalizedCatalogDto"
            ),
            (
                Path,
                1,
                "yssbi_lib::node_system::plan::model::GraphOutputRef"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/database/database_instance.rs",
        "yssbi_lib::database::database_instance",
        [
            (Use, 1, "yssbi_lib::graph::schema::ColumnSchema"),
            (Use, 1, "yssbi_lib::graph::schema::DataSchema"),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/analysis/projection/function_editor.rs",
        "yssbi_lib::node_system::analysis::projection::function_editor",
        [(Path, 1, "yssbi_lib::project::identity::ResourceRevision")],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/catalog/localization.rs",
        "yssbi_lib::node_system::catalog::localization",
        [(Path, 3, "yssbi_lib::project::identity::ResourceRevision")],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/document/history.rs",
        "yssbi_lib::node_system::document::history",
        [
            (Use, 1, "yssbi_lib::project::identity::HistoryEntryId"),
            (Use, 1, "yssbi_lib::project::identity::OperationId"),
            (Use, 1, "yssbi_lib::project::identity::ProjectRevision"),
            (Use, 1, "yssbi_lib::project::identity::ResourceRevision"),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/document/mod.rs",
        "yssbi_lib::node_system::document",
        [
            (Use, 1, "yssbi_lib::project::identity::HistoryEntryId"),
            (Use, 1, "yssbi_lib::project::identity::OperationId"),
            (Use, 1, "yssbi_lib::project::identity::ProjectRevision"),
            (Use, 1, "yssbi_lib::project::identity::ResourceRevision"),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/node_system/document/mutation.rs",
        "yssbi_lib::node_system::document::mutation",
        [
            (Use, 1, "yssbi_lib::project::identity::OperationId"),
            (Use, 1, "yssbi_lib::project::identity::ResourceRevision"),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/graph/analysis/mod.rs",
        "yssbi_lib::graph::analysis",
        [(
            Use,
            1,
            "yssbi_lib::execution::plan::basis::PlanCompilationBasis"
        ),],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/graph/compiler/mod.rs",
        "yssbi_lib::graph::compiler",
        [
            (
                Use,
                1,
                "yssbi_lib::execution::plan::basis::PlanCompilationBasis"
            ),
            (
                Use,
                1,
                "yssbi_lib::execution::plan::package::CompiledExecutionPackage"
            ),
        ],
    );
    debt_group!(
        entries,
        PROJECT_GRAPH_SPEC,
        "rust.internal.source-layer",
        "src-tauri/src/graph/runtime_state.rs",
        "yssbi_lib::graph::runtime_state",
        [(
            Use,
            1,
            "yssbi_lib::execution::plan::basis::PlanCompilationBasis"
        ),],
    );
}
