[package]
name = "yss-chart-document"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
serde.workspace = true
thiserror.workspace = true
yss-project-identity = { path = "../yss-project-identity" }
yss-project-layout = { path = "../yss-project-layout" }
yss-resource-naming = { path = "../yss-resource-naming" }

[dev-dependencies]
serde_json.workspace = true
