//! Stable inventory for the DataFrame catalog and its legacy identity subset.

#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum InterfaceKind {
    DataframeSource,
    Limit,
    Rename,
    Project,
    FilterRows,
    Decompose,
    Combine,
    Filter,
    SeriesSelect,
    IntRange,
    SeriesLength,
    SeriesCount,
    SeriesSum,
    SeriesMean,
    NumericCompare,
    StringCompare,
    Standardize,
    InverseStandardize,
    DummyInfo,
    TimeAlign,
    TimeUnary,
    TimeWindow,
    TimeLag,
    PanelAlign,
    PanelDifference,
}

#[derive(Clone, Copy)]
pub(super) struct NodeSpec {
    #[allow(dead_code)]
    pub legacy_name: Option<&'static str>,
    pub id: &'static str,
    pub title: &'static str,
    pub zh_title: &'static str,
    pub aliases: &'static [&'static str],
    pub zh_aliases: &'static [&'static str],
    pub interface: InterfaceKind,
    pub kernel: &'static str,
}

#[cfg(test)]
pub const LEGACY_NODE_IDS: &[(&str, &str)] = &[
    ("Get DataFrame", "yssbi.dataframe.source.get"),
    ("Limit DataFrame", "yssbi.dataframe.limit"),
    ("Decompose DataFrame", "yssbi.dataframe.decompose"),
    ("Combine DataFrame", "yssbi.dataframe.combine"),
    ("Filter DataFrame", "yssbi.dataframe.filter"),
    ("Get DataSeries", "yssbi.dataframe.series.select"),
    ("Int Range", "yssbi.dataframe.series.int_range"),
    ("DataSeries Length", "yssbi.dataframe.series.length"),
    ("DataSeries Sum", "yssbi.dataframe.series.sum"),
    ("DataSeries Mean", "yssbi.dataframe.series.mean"),
    (
        "DataSeries Greater Than (>)",
        "yssbi.dataframe.series.compare.greater",
    ),
    (
        "DataSeries Less Than (<)",
        "yssbi.dataframe.series.compare.less",
    ),
    (
        "DataSeries Greater Equal (>=)",
        "yssbi.dataframe.series.compare.greater_equal",
    ),
    (
        "DataSeries Less Equal (<=)",
        "yssbi.dataframe.series.compare.less_equal",
    ),
    (
        "DataSeries Equal (==)",
        "yssbi.dataframe.series.compare.equal",
    ),
    (
        "DataSeries Not Equal (!=)",
        "yssbi.dataframe.series.compare.not_equal",
    ),
    (
        "Standardize DataSeries",
        "yssbi.dataframe.series.standardize",
    ),
    (
        "Inverse Standardize DataSeries",
        "yssbi.dataframe.series.inverse_standardize",
    ),
    ("Add Dummy Info", "yssbi.dataframe.series.annotate_dummy"),
    ("TS Align", "yssbi.dataframe.timeseries.align"),
    ("TS Diff", "yssbi.dataframe.timeseries.difference"),
    ("TS Pct Change", "yssbi.dataframe.timeseries.percent_change"),
    ("TS Rolling Mean", "yssbi.dataframe.timeseries.rolling_mean"),
    ("TS Lag", "yssbi.dataframe.timeseries.lag"),
    ("XT Align", "yssbi.dataframe.panel.align"),
    ("XT Diff", "yssbi.dataframe.panel.difference"),
];

pub(super) const NODES: &[NodeSpec] = &[
    spec(
        "Get DataFrame",
        "yssbi.dataframe.source.get",
        "Get DataFrame",
        "获取数据框",
        &["data frame", "table", "source"],
        &["数据框", "表", "数据源"],
        InterfaceKind::DataframeSource,
    ),
    spec(
        "Limit DataFrame",
        "yssbi.dataframe.limit",
        "Limit DataFrame",
        "限制数据框行数",
        &["limit", "take rows", "head"],
        &["限制", "选取行", "前几行"],
        InterfaceKind::Limit,
    ),
    builtin_spec(
        "yssbi.dataframe.rename",
        "Rename DataFrame",
        "重命名数据框",
        &["rename column", "column name", "dataframe"],
        &["重命名列", "列名", "数据框"],
        InterfaceKind::Rename,
    ),
    builtin_spec(
        "yssbi.dataframe.project",
        "Project DataFrame",
        "投影数据框",
        &["select columns", "projection", "dataframe"],
        &["选择列", "投影", "数据框"],
        InterfaceKind::Project,
    ),
    builtin_spec(
        "yssbi.dataframe.filter.rows",
        "Filter Rows",
        "筛选行",
        &["where rows", "predicate", "filter"],
        &["筛选行", "谓词", "过滤"],
        InterfaceKind::FilterRows,
    ),
    spec(
        "Decompose DataFrame",
        "yssbi.dataframe.decompose",
        "Decompose DataFrame",
        "拆分数据框",
        &["columns", "split dataframe", "projection"],
        &["列", "拆分", "投影"],
        InterfaceKind::Decompose,
    ),
    spec(
        "Combine DataFrame",
        "yssbi.dataframe.combine",
        "Combine DataFrame",
        "合并数据框",
        &["column bind", "append columns", "dataframe"],
        &["按列合并", "追加列", "数据框"],
        InterfaceKind::Combine,
    ),
    spec(
        "Filter DataFrame",
        "yssbi.dataframe.filter",
        "Filter DataFrame",
        "筛选数据框",
        &["where", "predicate", "mask"],
        &["条件筛选", "谓词", "掩码"],
        InterfaceKind::Filter,
    ),
    spec(
        "Get DataSeries",
        "yssbi.dataframe.series.select",
        "Get DataSeries",
        "获取数据序列",
        &["column", "series", "select"],
        &["列", "序列", "选择"],
        InterfaceKind::SeriesSelect,
    ),
    spec(
        "Int Range",
        "yssbi.dataframe.series.int_range",
        "Integer Range",
        "整数序列",
        &["range", "sequence", "integers"],
        &["范围", "序列", "整数"],
        InterfaceKind::IntRange,
    ),
    spec(
        "DataSeries Length",
        "yssbi.dataframe.series.length",
        "DataSeries Length",
        "序列长度",
        &["count", "length", "series"],
        &["计数", "长度", "序列"],
        InterfaceKind::SeriesLength,
    ),
    builtin_spec(
        "yssbi.dataframe.series.count",
        "DataSeries Count",
        "序列非空计数",
        &["count", "non-null", "series"],
        &["计数", "非空", "序列"],
        InterfaceKind::SeriesCount,
    ),
    spec(
        "DataSeries Sum",
        "yssbi.dataframe.series.sum",
        "DataSeries Sum",
        "序列求和",
        &["sum", "aggregate", "series"],
        &["求和", "聚合", "序列"],
        InterfaceKind::SeriesSum,
    ),
    spec(
        "DataSeries Mean",
        "yssbi.dataframe.series.mean",
        "DataSeries Mean",
        "序列均值",
        &["mean", "average", "series"],
        &["均值", "平均", "序列"],
        InterfaceKind::SeriesMean,
    ),
    spec(
        "DataSeries Greater Than (>)",
        "yssbi.dataframe.series.compare.greater",
        "DataSeries Greater Than",
        "序列大于",
        &["greater than", ">", "element-wise"],
        &["大于", ">", "逐元素"],
        InterfaceKind::NumericCompare,
    ),
    spec(
        "DataSeries Less Than (<)",
        "yssbi.dataframe.series.compare.less",
        "DataSeries Less Than",
        "序列小于",
        &["less than", "<", "element-wise"],
        &["小于", "<", "逐元素"],
        InterfaceKind::NumericCompare,
    ),
    spec(
        "DataSeries Greater Equal (>=)",
        "yssbi.dataframe.series.compare.greater_equal",
        "DataSeries Greater or Equal",
        "序列大于等于",
        &["greater or equal", ">=", "element-wise"],
        &["大于等于", ">=", "逐元素"],
        InterfaceKind::NumericCompare,
    ),
    spec(
        "DataSeries Less Equal (<=)",
        "yssbi.dataframe.series.compare.less_equal",
        "DataSeries Less or Equal",
        "序列小于等于",
        &["less or equal", "<=", "element-wise"],
        &["小于等于", "<=", "逐元素"],
        InterfaceKind::NumericCompare,
    ),
    spec(
        "DataSeries Equal (==)",
        "yssbi.dataframe.series.compare.equal",
        "DataSeries Equal",
        "序列等于",
        &["equal", "==", "element-wise"],
        &["等于", "==", "逐元素"],
        InterfaceKind::NumericCompare,
    ),
    spec(
        "DataSeries Not Equal (!=)",
        "yssbi.dataframe.series.compare.not_equal",
        "DataSeries Not Equal",
        "序列不等于",
        &["not equal", "!=", "element-wise"],
        &["不等于", "!=", "逐元素"],
        InterfaceKind::NumericCompare,
    ),
    builtin_spec(
        "yssbi.dataframe.series.compare.string.equal",
        "String DataSeries Equal",
        "字符串序列等于",
        &["string equal", "text ==", "element-wise"],
        &["字符串等于", "文本 ==", "逐元素"],
        InterfaceKind::StringCompare,
    ),
    builtin_spec(
        "yssbi.dataframe.series.compare.string.not_equal",
        "String DataSeries Not Equal",
        "字符串序列不等于",
        &["string not equal", "text !=", "element-wise"],
        &["字符串不等于", "文本 !=", "逐元素"],
        InterfaceKind::StringCompare,
    ),
    spec(
        "Standardize DataSeries",
        "yssbi.dataframe.series.standardize",
        "Standardize DataSeries",
        "标准化数据序列",
        &["z-score", "standardize", "scale"],
        &["标准分", "标准化", "缩放"],
        InterfaceKind::Standardize,
    ),
    spec(
        "Inverse Standardize DataSeries",
        "yssbi.dataframe.series.inverse_standardize",
        "Inverse Standardize DataSeries",
        "逆标准化数据序列",
        &["inverse z-score", "unscale", "restore"],
        &["逆标准分", "还原缩放", "恢复"],
        InterfaceKind::InverseStandardize,
    ),
    spec(
        "Add Dummy Info",
        "yssbi.dataframe.series.annotate_dummy",
        "Add Dummy Information",
        "添加虚拟变量信息",
        &["dummy variable", "indicator", "metadata"],
        &["虚拟变量", "指示变量", "元数据"],
        InterfaceKind::DummyInfo,
    ),
    spec(
        "TS Align",
        "yssbi.dataframe.timeseries.align",
        "Align Time Series",
        "对齐时间序列",
        &["ts align", "frequency", "time index"],
        &["时序对齐", "频率", "时间索引"],
        InterfaceKind::TimeAlign,
    ),
    spec(
        "TS Diff",
        "yssbi.dataframe.timeseries.difference",
        "Time-Series Difference",
        "时间序列差分",
        &["difference", "diff", "stationarity"],
        &["差分", "平稳性"],
        InterfaceKind::TimeUnary,
    ),
    spec(
        "TS Pct Change",
        "yssbi.dataframe.timeseries.percent_change",
        "Time-Series Percent Change",
        "时间序列百分比变化",
        &["percent change", "growth rate", "returns"],
        &["百分比变化", "增长率", "收益率"],
        InterfaceKind::TimeUnary,
    ),
    spec(
        "TS Rolling Mean",
        "yssbi.dataframe.timeseries.rolling_mean",
        "Time-Series Rolling Mean",
        "时间序列滚动均值",
        &["moving average", "rolling window", "smoothing"],
        &["移动平均", "滚动窗口", "平滑"],
        InterfaceKind::TimeWindow,
    ),
    spec(
        "TS Lag",
        "yssbi.dataframe.timeseries.lag",
        "Lag Time Series",
        "时间序列滞后",
        &["lag", "lead", "shift"],
        &["滞后", "超前", "平移"],
        InterfaceKind::TimeLag,
    ),
    spec(
        "XT Align",
        "yssbi.dataframe.panel.align",
        "Align Panel Data",
        "对齐面板数据",
        &["xtset", "panel index", "entity time"],
        &["面板设定", "面板索引", "个体时间"],
        InterfaceKind::PanelAlign,
    ),
    spec(
        "XT Diff",
        "yssbi.dataframe.panel.difference",
        "Panel Difference",
        "面板数据差分",
        &["panel difference", "within entity", "first difference"],
        &["面板差分", "组内", "一阶差分"],
        InterfaceKind::PanelDifference,
    ),
];

const fn spec(
    legacy_name: &'static str,
    id: &'static str,
    title: &'static str,
    zh_title: &'static str,
    aliases: &'static [&'static str],
    zh_aliases: &'static [&'static str],
    interface: InterfaceKind,
) -> NodeSpec {
    NodeSpec {
        legacy_name: Some(legacy_name),
        id,
        title,
        zh_title,
        aliases,
        zh_aliases,
        interface,
        kernel: id,
    }
}

const fn builtin_spec(
    id: &'static str,
    title: &'static str,
    zh_title: &'static str,
    aliases: &'static [&'static str],
    zh_aliases: &'static [&'static str],
    interface: InterfaceKind,
) -> NodeSpec {
    NodeSpec {
        legacy_name: None,
        id,
        title,
        zh_title,
        aliases,
        zh_aliases,
        interface,
        kernel: id,
    }
}
