[package]
name = "yss-sci"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
yss-math-expr = { path = "../yss-math-expr" }
yss-sci-contract = { path = "../yss-sci-contract" }
yss-sci-linalg = { path = "../yss-sci-linalg" }
num-traits.workspace = true
serde.workspace = true
statrs.workspace = true
rand.workspace = true

[dev-dependencies]
serde_json.workspace = true
csv = "1.3"
