use super::engine::DatabaseEngine;
use serde::{Deserialize, Serialize};

/// Persisted identity and source declaration for one project database.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DatabaseDecl {
    pub id: super::identity::DatabaseId,
    pub engine: DatabaseEngine,
    pub schema_version: u32,
    pub required: bool,
    /// Display name generated by the backend when importing a database.
    pub name: Box<str>,
}
