export const FRONTEND_DIAGNOSTIC_BATCH_MAX_ENTRIES = 32;
export const FRONTEND_DIAGNOSTIC_BATCH_MAX_PENDING = 256;
export const FRONTEND_DIAGNOSTIC_BATCH_MAX_DELAY_MS = 100;
export const FRONTEND_DIAGNOSTIC_MESSAGE_MAX_BYTES = 16_384;
