[package]
name = "yss-project-registry"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
serde.workspace = true
thiserror.workspace = true
yss-path-display = { path = "../yss-path-display" }
yss-project-discovery = { path = "../yss-project-discovery" }
yss-project-filesystem = { path = "../yss-project-filesystem" }
yss-project-identity = { path = "../yss-project-identity" }
yss-project-layout = { path = "../yss-project-layout" }
yss-project-progress = { path = "../yss-project-progress" }
yss-project-registry-contract = { path = "../yss-project-registry-contract" }

[dev-dependencies]
tokio.workspace = true
