use super::engine::DatabaseEngine;
use serde::{Deserialize, Serialize};

/// Persisted identity and source declaration for one project database.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DatabaseDecl {
    pub id: String,
    pub engine: DatabaseEngine,
    pub schema_version: u32,
    pub required: bool,
    /// Display name generated by the backend when importing a database.
    pub name: String,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn database_declaration_preserves_camel_case_wire_and_required_name() {
        let declaration = DatabaseDecl {
            id: "sales".into(),
            engine: DatabaseEngine::InMemory {
                name: "sales".into(),
            },
            schema_version: 1,
            required: false,
            name: "Sales".into(),
        };

        assert_eq!(
            serde_json::to_value(&declaration).unwrap(),
            json!({
                "id": "sales",
                "engine": {"inMemory": {"name": "sales"}},
                "schemaVersion": 1,
                "required": false,
                "name": "Sales"
            })
        );

        let mut value = serde_json::to_value(declaration).unwrap();
        value.as_object_mut().unwrap().remove("name");
        let error = serde_json::from_value::<DatabaseDecl>(value).unwrap_err();
        assert!(error.to_string().contains("missing field `name`"));
    }
}
