//! Numeric table columns generated by parameters, without reading observations.
use super::EditorSchemaResolver;
use crate::GraphSchemaIssue;
use yss_graph_document::NodeId;
use yss_node_protocol::{RelationalScalarType, SchemaColumnRef, SchemaField};

impl EditorSchemaResolver<'_> {
    pub(super) fn resolve_generated_numeric_table(
        &self,
        node_id: NodeId,
        parameter_key: &str,
        prefixes: &[&str],
        run_number: bool,
    ) -> Result<Vec<SchemaField>, GraphSchemaIssue> {
        let node = self
            .document
            .nodes
            .get(&node_id)
            .ok_or(GraphSchemaIssue::MissingResource)?;
        let protocol = self
            .registry
            .protocol(&node.node_type)
            .ok_or(GraphSchemaIssue::MissingResource)?;
        let parameter = protocol
            .parameters
            .iter()
            .find(|p| p.key.as_str() == parameter_key)
            .filter(|p| protocol.parameters.is_visible(p, &node.parameters))
            .ok_or(GraphSchemaIssue::InvalidParameter)?;
        let count = crate::parameter_projection::effective_parameter_value(node, parameter)
            .and_then(|v| v.as_u64())
            .and_then(|v| usize::try_from(v).ok())
            .filter(|&n| n > 0)
            .ok_or(GraphSchemaIssue::InvalidParameter)?;
        let length = count
            .checked_mul(prefixes.len())
            .and_then(|n| n.checked_add(usize::from(run_number)))
            .ok_or(GraphSchemaIssue::InvalidParameter)?;
        let mut fields = Vec::new();
        // Reject allocation overflow/failure instead of imposing a fixed number of axes/factors.
        fields
            .try_reserve_exact(length)
            .map_err(|_| GraphSchemaIssue::InvalidParameter)?;
        let field = |name: String| SchemaField {
            name: SchemaColumnRef(name.into()),
            scalar_type: RelationalScalarType::Known(yss_data_contract::SemanticType::Numeric),
            lineage: None,
        };
        if run_number {
            fields.push(field("run".into()));
        }
        for prefix in prefixes {
            for index in 1..=count {
                fields.push(field(format!("{prefix}{index}")));
            }
        }
        Ok(fields)
    }
}
