[package]
name = "yss-node-kernel"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
yss-canonical-hash = { path = "../yss-canonical-hash" }
yss-data-contract = { path = "../yss-data-contract" }
yss-relational-contract = { path = "../yss-relational-contract" }
yss-sci-contract = { path = "../yss-sci-contract" }
yss-sci-runtime = { path = "../yss-sci-runtime" }
thiserror.workspace = true
