export type DataType =
    | "int8"
    | "int16"
    | "int32"
    | "int64"
    | "uint32"
    | "uint64"
    | "float32"
    | "float64"
    | "bool"
    | "string"
    | "date"
    | "datetime"
    | "object"
    | "array"
    | "dataframe"
