//! Stable inventory for statistical node families.

#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum Stage {
    Fit,
    Summary,
    Predict,
    Test,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) enum Family {
    Adf,
    Ols,
    Gls,
    Iv2sls,
    IvLiml,
    Logit,
    Probit,
    Prais,
    Panel,
    PanelDid,
    Var,
    Vec,
    VecRank,
    Prediction,
}

#[derive(Clone, Copy)]
pub(super) struct NodeSpec {
    pub id: &'static str,
    pub title: &'static str,
    pub zh_title: &'static str,
    pub aliases: &'static [&'static str],
    pub zh_aliases: &'static [&'static str],
    pub family: Family,
    pub stage: Stage,
}

pub(super) const NODES: &[NodeSpec] = &[
    node(
        "yssbi.statistics.adf.test",
        "Dickey–Fuller / Augmented Dickey–Fuller",
        "DF / ADF 单位根检验",
        &["DF", "ADF", "unit root", "Dickey-Fuller"],
        &["单位根", "迪基-富勒"],
        Family::Adf,
        Stage::Test,
    ),
    node(
        "yssbi.statistics.adf.summary",
        "DF / ADF Summary",
        "DF / ADF 汇总",
        &["ADF report", "critical values", "unit root"],
        &["ADF 报告", "临界值", "单位根"],
        Family::Adf,
        Stage::Summary,
    ),
    node(
        "yssbi.statistics.ols.fit",
        "Fit OLS",
        "拟合 OLS",
        &["OLS", "ordinary least squares", "linear regression"],
        &["普通最小二乘", "线性回归"],
        Family::Ols,
        Stage::Fit,
    ),
    node(
        "yssbi.statistics.ols.summary",
        "OLS Summary",
        "OLS 汇总",
        &["OLS report", "regression table", "diagnostics"],
        &["回归表", "诊断"],
        Family::Ols,
        Stage::Summary,
    ),
    node(
        "yssbi.statistics.gls.fit",
        "Fit GLS",
        "拟合 GLS",
        &["GLS", "generalized least squares", "linear model"],
        &["广义最小二乘", "线性模型"],
        Family::Gls,
        Stage::Fit,
    ),
    node(
        "yssbi.statistics.gls.summary",
        "GLS Summary",
        "GLS 汇总",
        &["GLS report", "regression table", "diagnostics"],
        &["GLS 报告", "回归表", "诊断"],
        Family::Gls,
        Stage::Summary,
    ),
    node(
        "yssbi.statistics.iv.2sls.summary",
        "IV 2SLS Summary",
        "工具变量 2SLS 汇总",
        &["2SLS report", "instrumental variables", "first stage"],
        &["2SLS 报告", "工具变量", "第一阶段"],
        Family::Iv2sls,
        Stage::Summary,
    ),
    node(
        "yssbi.statistics.iv.liml.summary",
        "IV LIML Summary",
        "工具变量 LIML 汇总",
        &[
            "LIML",
            "limited information maximum likelihood",
            "weak instruments",
        ],
        &["有限信息极大似然", "弱工具变量"],
        Family::IvLiml,
        Stage::Summary,
    ),
    node(
        "yssbi.statistics.logit.fit",
        "Fit Logit",
        "拟合 Logit",
        &["logit", "logistic regression", "binary classifier"],
        &["逻辑回归", "二元分类"],
        Family::Logit,
        Stage::Fit,
    ),
    node(
        "yssbi.statistics.logit.summary",
        "Logit Summary",
        "Logit 汇总",
        &["logit report", "odds", "maximum likelihood"],
        &["Logit 报告", "胜算", "极大似然"],
        Family::Logit,
        Stage::Summary,
    ),
    node(
        "yssbi.statistics.panel.summary",
        "Panel Model Summary",
        "面板模型汇总",
        &["xtreg", "panel regression", "within estimator"],
        &["面板回归", "组内估计"],
        Family::Panel,
        Stage::Summary,
    ),
    node(
        "yssbi.statistics.panel.did.twfe",
        "Panel DID (TWFE)",
        "面板双重差分（双向固定效应）",
        &[
            "difference in differences",
            "TWFE",
            "event study",
            "parallel trends",
        ],
        &["双重差分", "双向固定效应", "事件研究", "平行趋势"],
        Family::PanelDid,
        Stage::Summary,
    ),
    node(
        "yssbi.statistics.prais.fit",
        "Fit Prais–Winsten",
        "拟合 Prais–Winsten",
        &["Prais-Winsten", "serial correlation", "FGLS"],
        &["普莱斯-温斯坦", "序列相关", "可行广义最小二乘"],
        Family::Prais,
        Stage::Fit,
    ),
    node(
        "yssbi.statistics.prais.summary",
        "Prais–Winsten Summary",
        "Prais–Winsten 汇总",
        &["Prais report", "rho", "Durbin-Watson"],
        &["Prais 报告", "自相关系数", "德宾-沃森"],
        Family::Prais,
        Stage::Summary,
    ),
    node(
        "yssbi.statistics.linear.predict",
        "Linear Prediction",
        "线性模型预测",
        &["predict", "fitted values", "linear model"],
        &["预测", "拟合值", "线性模型"],
        Family::Prediction,
        Stage::Predict,
    ),
    node(
        "yssbi.statistics.logit.predict",
        "Logit Prediction",
        "Logit 预测",
        &["predict probability", "logit", "classification"],
        &["预测概率", "逻辑回归", "分类"],
        Family::Logit,
        Stage::Predict,
    ),
    node(
        "yssbi.statistics.probit.predict",
        "Probit Prediction",
        "Probit 预测",
        &["predict probability", "probit", "normal CDF"],
        &["预测概率", "概率单位", "正态分布函数"],
        Family::Probit,
        Stage::Predict,
    ),
    node(
        "yssbi.statistics.probit.fit",
        "Fit Probit",
        "拟合 Probit",
        &["probit", "normal link", "binary classifier"],
        &["概率单位", "正态链接", "二元分类"],
        Family::Probit,
        Stage::Fit,
    ),
    node(
        "yssbi.statistics.probit.summary",
        "Probit Summary",
        "Probit 汇总",
        &["probit report", "marginal effects", "maximum likelihood"],
        &["Probit 报告", "边际效应", "极大似然"],
        Family::Probit,
        Stage::Summary,
    ),
    node(
        "yssbi.statistics.var.lag_order",
        "VAR Lag-order Selection",
        "VAR 滞后阶数选择",
        &["varsoc", "AIC", "BIC", "HQIC"],
        &["滞后阶数", "赤池信息准则", "贝叶斯信息准则"],
        Family::Var,
        Stage::Test,
    ),
    node(
        "yssbi.statistics.var.summary",
        "VAR Summary",
        "VAR 汇总",
        &["vector autoregression", "VAR", "multivariate time series"],
        &["向量自回归", "多变量时间序列"],
        Family::Var,
        Stage::Summary,
    ),
    node(
        "yssbi.statistics.vec.fit",
        "Vector Error-correction Model",
        "向量误差修正模型",
        &["VECM", "cointegration", "error correction"],
        &["向量误差修正", "协整", "误差修正"],
        Family::Vec,
        Stage::Fit,
    ),
    node(
        "yssbi.statistics.vec.rank_test",
        "Johansen Cointegration Rank",
        "Johansen 协整秩检验",
        &["Johansen", "vecrank", "trace test", "maximum eigenvalue"],
        &["约翰森", "协整秩", "迹检验", "最大特征值"],
        Family::VecRank,
        Stage::Test,
    ),
    node(
        "yssbi.statistics.wls.fit",
        "Fit WLS",
        "拟合 WLS",
        &["weighted least squares", "WLS", "weights"],
        &["加权最小二乘", "权重"],
        Family::Ols,
        Stage::Fit,
    ),
    node(
        "yssbi.statistics.wls.summary",
        "WLS Summary",
        "WLS 汇总",
        &["WLS report", "weighted regression", "diagnostics"],
        &["WLS 报告", "加权回归", "诊断"],
        Family::Ols,
        Stage::Summary,
    ),
];

const fn node(
    id: &'static str,
    title: &'static str,
    zh_title: &'static str,
    aliases: &'static [&'static str],
    zh_aliases: &'static [&'static str],
    family: Family,
    stage: Stage,
) -> NodeSpec {
    NodeSpec {
        id,
        title,
        zh_title,
        aliases,
        zh_aliases,
        family,
        stage,
    }
}
