[package]
name = "yss-graph-compiler"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
thiserror.workspace = true
yss-graph-analysis = { path = "../yss-graph-analysis" }
yss-graph-analysis-contract = { path = "../yss-graph-analysis-contract" }
yss-graph-document = { path = "../yss-graph-document" }
yss-graph-protocol = { path = "../yss-graph-protocol" }
yss-graph-registry = { path = "../yss-graph-registry" }
